import{teacherLogin,teacherLogout,resetTeacherPassword,changeTeacherPassword,watchTeacher,adminSnapshot,setAccessMode,saveClass,setClassActive,addStudents,setStudentActive,resetStudentPassword}from'./cloud.js?v=20260913-teacher-reset';
const $=s=>document.querySelector(s);let data=null,lastCredentials=[];
function msg(text,error=false,target='#status'){const el=$(target);el.textContent=text;el.className='message'+(error?' error':'');el.classList.remove('hidden');}
function date(v){try{return v?.toDate().toLocaleString()||'—'}catch{return'—'}}
async function load(){msg('Loading…');try{data=await adminSnapshot();render();$('#status').classList.add('hidden')}catch(e){msg(e.message,true)}}
function render(){
  $('#m-total').textContent=Number(data.metrics.totalVisits||0).toLocaleString();$('#m-unique').textContent=Number(data.metrics.uniqueVisitors||0).toLocaleString();$('#m-students').textContent=data.students.filter(s=>s.studentId).length;$('#m-active').textContent=data.students.filter(s=>s.studentId&&s.active).length;$('#access-mode').value=data.settings.accessMode||'public';
  const classes=data.classes.sort((a,b)=>(a.name||a.id).localeCompare(b.name||b.id));
  $('#class-list').innerHTML=classes.map(c=>`<p><strong>${esc(c.name||c.id)}</strong> (${esc(c.id)}) <button data-class="${esc(c.id)}" data-active="${!c.active}">${c.active?'Deactivate':'Activate'}</button></p>`).join('')||'<p>No classes yet.</p>';
  const opts=classes.filter(c=>c.active).map(c=>`<option value="${esc(c.id)}">${esc(c.name||c.id)}</option>`).join('');$('#student-class').innerHTML=opts;$('#filter-class').innerHTML='<option value="">All classes</option>'+classes.map(c=>`<option value="${esc(c.id)}">${esc(c.name||c.id)}</option>`).join('');renderStudents();
  $('#activity-table').innerHTML=data.activities.map(a=>`<tr><td>${esc(a.studentId)}</td><td>${esc(a.classId)}</td><td>${esc(a.label)}</td><td>${a.unit||'—'}</td><td>${esc(a.score)}</td><td>${a.xp||0}</td><td>${date(a.completedAt)}</td></tr>`).join('')||'<tr><td colspan="7">No completed activities yet.</td></tr>';
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderStudents(){if(!data)return;const filter=$('#filter-class').value,stats=new Map(data.stats.map(s=>[s.id,s]));$('#student-table').innerHTML=data.students.filter(s=>s.studentId&&(!filter||s.classId===filter)).sort((a,b)=>(a.classId+a.studentId).localeCompare(b.classId+b.studentId)).map(s=>{const p=stats.get(s.id)||{};return`<tr><td>${esc(s.studentId)}</td><td>${esc(s.classId)}</td><td>${esc([s.firstName,s.lastName].filter(Boolean).join(' ')||'—')}</td><td>${s.visits||0}</td><td>${p.xp||0}</td><td>${p.masteredWords||0}</td><td>${s.recoveryMethod==='email'?'Student email':'Teacher reset'}</td><td>${s.mustChangePassword?'Change required':'Private set'}</td><td>${date(s.lastVisit)}</td><td><button data-student="${esc(s.studentId)}" data-active="${!s.active}">${s.active?'Disable':'Enable'}</button> <button data-reset="${esc(s.studentId)}">Reset password</button></td></tr>`}).join('')||'<tr><td colspan="10">No matching secure student accounts.</td></tr>'}
watchTeacher(user=>{$('#login').classList.toggle('hidden',!!user);$('#dashboard').classList.toggle('hidden',!user);$('#logout').classList.toggle('hidden',!user);if(user)load()});
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();try{await teacherLogin($('#email').value,$('#password').value);$('#password').value=''}catch(x){msg(x.message,true,'#login-msg')}});
$('#forgot').onclick=async()=>{try{await resetTeacherPassword($('#email').value);msg('Password reset email sent. Check the inbox and spam folder.','', '#login-msg')}catch(x){msg(x.message,true,'#login-msg')}};
$('#logout').onclick=teacherLogout;$('#refresh').onclick=load;$('#filter-class').onchange=renderStudents;
$('#save-mode').onclick=async()=>{try{await setAccessMode($('#access-mode').value);msg('Access mode saved.');await load()}catch(x){msg(x.message,true)}};
$('#class-form').onsubmit=async e=>{e.preventDefault();try{await saveClass($('#class-code').value,$('#class-name').value);e.target.reset();msg('Class saved.');await load()}catch(x){msg(x.message,true)}};
$('#students-form').onsubmit=async e=>{e.preventDefault();try{const result=await addStudents($('#student-class').value,$('#student-ids').value.split(/\r?\n/));lastCredentials=result.credentials||[];const created=lastCredentials.filter(x=>x.password);$('#credentials-preview').value=created.map(x=>`${x.studentId} | ${x.classId} | Temporary: ${x.password}`).join('\n')||'No new passwords were created. Existing accounts were left unchanged.';$('#credentials-box').classList.remove('hidden');e.target.reset();msg(`${result.count} secure student account${result.count===1?'':'s'} processed; ${created.length} temporary password${created.length===1?'':'s'} created.`);await load()}catch(x){msg(x.message,true)}};
$('#download-credentials').onclick=()=>{const rows=[['Student ID','Class','Temporary password','Required action'],...lastCredentials.filter(x=>x.password).map(x=>[x.studentId,x.classId,x.password,'Create a private password at first login'])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='oqab-academy-student-credentials.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#password-form').onsubmit=async e=>{e.preventDefault();try{await changeTeacherPassword($('#current-password').value,$('#new-password').value);e.target.reset();msg('Password changed successfully.')}catch(x){msg(x.message,true)}};
$('#class-list').onclick=async e=>{const b=e.target.closest('[data-class]');if(!b)return;try{await setClassActive(b.dataset.class,b.dataset.active==='true');await load()}catch(x){msg(x.message,true)}};
$('#student-table').onclick=async e=>{const reset=e.target.closest('[data-reset]'),toggle=e.target.closest('[data-student]');try{if(reset){if(!confirm(`Create a new temporary password for ${reset.dataset.reset}?`))return;const result=await resetStudentPassword(reset.dataset.reset);lastCredentials=[{studentId:result.studentId,classId:data.students.find(s=>s.studentId===result.studentId)?.classId||'',password:result.password}];$('#credentials-preview').value=`${result.studentId} | ${lastCredentials[0].classId} | ${result.password}`;$('#credentials-box').classList.remove('hidden');msg('Temporary password created. Download or copy it now.');return;}if(toggle){await setStudentActive(toggle.dataset.student,toggle.dataset.active==='true');await load();}}catch(x){msg(x.message,true)}};
