// Level B, Unit 8. Includes multiple meanings, context practice, and offline IPA.
vocabRows.push(
  [8,"abnormal","adj.","not normal, usual, typical, or expected.","The nurse noticed an abnormal change in the patient's temperature.","unusual, irregular, atypical","normal, usual, typical","⚠️ 📈","Something noticeably outside the usual pattern","abnormal behaviour","Abnormal describes something that differs from what is normally expected; it does not always mean dangerous."],
  [8,"capsize","v.","to overturn in water, especially a boat; to cause a boat to overturn.","A sudden wave could capsize the small fishing boat.","overturn, tip over, upset","right, steady, stabilise","⛵ 🌊","A boat turning upside down in water","capsize a boat","Capsize is used mainly for boats and other vessels in water."],
  [8,"catastrophe","n.","a sudden event causing great damage, suffering, or loss; a complete and disastrous failure.","Early warnings helped prevent the storm from becoming a greater catastrophe.","disaster, calamity, devastation","success, blessing, triumph","🌪️ 🆘","A disaster with very serious consequences","a natural catastrophe","Catastrophe may describe a large disaster or, less formally, a complete failure."],
  [8,"decrease","v., n.","(v.) to become or make less in size, number, strength, or amount; (n.) a reduction.","Regular rainfall caused a decrease in the need for extra irrigation.","reduce, decline, diminish; reduction","increase, rise, grow; growth","📉 ➖","A quantity becoming smaller","decrease in temperature","As a verb, the stress is usually on the second syllable; as a noun, it is usually on the first."],
  [8,"disputatious","adj.","fond of arguing or disagreeing; inclined to quarrel.","The disputatious speaker challenged every suggestion, even the sensible ones.","argumentative, quarrelsome, contentious","agreeable, peaceful, cooperative","🗣️ ⚡","Ready to argue about almost anything","a disputatious person","Disputatious describes a person or manner that tends to provoke arguments."],
  [8,"evict","v.","to force a person to leave property, usually by legal authority; to remove someone from a place.","A landlord must follow the law before attempting to evict a tenant.","expel, remove, eject","admit, welcome, house","🏠 ➡️","Being required to leave a place","evict a tenant","Evict commonly refers to legally removing someone from a home or other property."],
  [8,"flourish","v., n.","(v.) to grow or develop successfully; to wave or display dramatically; (n.) healthy growth, a bold gesture, an ornamental curve, or a showy addition.","The community garden began to flourish after volunteers improved the soil.","thrive, prosper, bloom; wave","wither, decline, fail","🌱 ✨","Growing strongly or making a dramatic display","flourish under good care","Flourish can describe successful growth or a dramatic movement, decoration, or musical phrase."],
  [8,"incentive","n., adj.","(n.) something that encourages a person to act or work harder; (adj.) intended to encourage action.","The reading certificate gave students an incentive to finish another book.","motivation, encouragement, stimulus","deterrent, discouragement, obstacle","🎁 ➜","A reason or reward that encourages action","an incentive to improve","An incentive may be a reward, benefit, or other motivating reason."],
  [8,"insubordinate","adj.","disobedient to authority; refusing to follow reasonable orders or rules.","The employee received a warning for repeatedly being insubordinate to her supervisor.","disobedient, defiant, rebellious","obedient, respectful, compliant","🚫 📋","Refusing to obey proper authority","insubordinate conduct","Insubordinate is used when someone deliberately refuses the authority of a supervisor or leader."],
  [8,"legible","adj.","clear enough to be read.","Please write in dark ink so that every answer is legible.","readable, clear, decipherable","illegible, unreadable, unclear","✍️ ✅","Writing that can be read without difficulty","legible handwriting","Legible refers to how easy writing or print is to read, not how easy its ideas are to understand."],
  [8,"nub","n.","the central point or essential part of a matter; a small lump, knob, or remaining piece.","The nub of the debate was whether the plan would be fair to everyone.","gist, essence, core; knob","detail, surface, whole","🎯 🔹","The essential point or a small projecting piece","the nub of the problem","Nub often appears in the phrase the nub of the matter, meaning its central point."],
  [8,"onslaught","n.","a fierce, powerful attack; a sudden and overwhelming amount of something.","The help desk received an onslaught of questions after the new system opened.","assault, attack, barrage","defence, retreat, trickle","🌊 💥","A forceful attack or overwhelming rush","an onslaught of criticism","Onslaught may be a physical attack or a figurative flood of questions, criticism, or demands."],
  [8,"ordain","v.","to order or establish officially; to appoint or consecrate someone as a religious leader; to determine by fate or authority.","The rules ordain that every safety check must be recorded.","decree, command, appoint, consecrate","forbid, revoke, dismiss","📜 ✋","Making something official by authority","ordain a minister","Ordain has formal uses in laws and decrees and a specialised religious meaning."],
  [8,"outstrip","v.","to go faster or farther than; to exceed or surpass in performance, growth, or amount.","Demand for the popular course began to outstrip the number of available places.","surpass, exceed, overtake","trail, lag, fall behind","🏃 💨","Moving ahead of or exceeding something else","outstrip the competition","Outstrip may refer to physical speed or to one amount or performance becoming greater than another."],
  [8,"pervade","v.","to spread through and be present in every part of a place, thing, or group.","The smell of fresh bread began to pervade the entire building.","fill, permeate, spread through","leave, disappear, withdraw","🌫️ 🏠","Spreading throughout every part","pervade the room","Pervade is often used for smells, feelings, sounds, or ideas that spread everywhere."],
  [8,"prudent","adj.","wise, careful, and showing good judgment about future risks or results.","It is prudent to save a copy of your work before closing the computer.","wise, cautious, sensible","reckless, careless, unwise","🧠 🛡️","Thinking carefully before acting","a prudent decision","A prudent choice considers both present needs and possible future consequences."],
  [8,"quench","v.","to satisfy thirst; to extinguish a fire; to stop or suppress something; to cool hot metal rapidly.","Cold water helped the hikers quench their thirst.","satisfy, extinguish, suppress, cool","ignite, kindle, intensify","🥤 🔥","Satisfying thirst or putting out a flame","quench one's thirst","Quench is used for thirst, fire, strong feelings, and the rapid cooling of hot metal."],
  [8,"remnant","n., adj.","(n.) a small part left after the rest has been used, destroyed, or removed; (adj.) remaining.","Only a small remnant of the ancient wall still stands.","remainder, residue, fragment","whole, entirety, total","🧩 ⏳","A small piece that remains","a remnant of the past","As an adjective, remnant means left over, as in remnant fabric."],
  [8,"simultaneous","adj.","happening, existing, or done at exactly the same time.","The two runners crossed the finish line in an almost simultaneous finish.","concurrent, coinciding, synchronous","separate, successive, consecutive","⏱️ ↔️","Two or more events occurring together","simultaneous events","Simultaneous refers to timing; events can be simultaneous even when they occur in different places."],
  [8,"swerve","v., n.","(v.) to turn aside suddenly from a straight course; to change direction or purpose; (n.) a sudden turn aside.","The cyclist had to swerve to avoid a branch in the road.","veer, turn aside, deviate","continue, straighten, remain","🚗 ↪️","A sudden change away from a course","swerve to avoid","Swerve may describe physical movement or a sudden change from a plan or principle."]
);

practiceRows.push(
  ["abnormal",["The scan revealed an ______ pattern that required further study.","An ______ amount of rain fell during the normally dry month.","The technician investigated the machine's ______ noise."],["legible","prudent","simultaneous"]],
  ["capsize",["Strong crosswinds threatened to ______ the small sailboat.","Passengers were told to stay seated so the canoe would not ______.","The overloaded vessel might ______ in rough water."],["swerve","outstrip","quench"]],
  ["catastrophe",["The earthquake was a national ______ that displaced thousands of families.","Careful planning prevented the technical failure from becoming a ______.","Losing the only copy of the research would be a ______."],["incentive","remnant","decrease"]],
  ["decrease",["Turning off unused lights can ______ the amount of electricity consumed.","The chart shows a steady ______ in water use.","As the storm moved away, the wind speed began to ______."],["flourish","outstrip","pervade"]],
  ["disputatious",["The ______ guest argued about every decision at the meeting.","A ______ tone can turn a useful discussion into a quarrel.","Because he was naturally ______, he rarely accepted an idea without arguing."],["prudent","legible","abnormal"]],
  ["evict",["The court order allowed the owner to ______ tenants who had broken the agreement.","Officials may ______ anyone who enters the restricted area.","The landlord could not legally ______ the family without proper notice."],["ordain","pervade","quench"]],
  ["flourish",["These plants ______ when they receive enough sunlight and water.","The actor entered with a dramatic ______ of his cape.","Small businesses can ______ when a community supports them."],["decrease","swerve","evict"]],
  ["incentive",["A prize offered an extra ______ for completing the reading challenge.","Lower fees may provide an ______ for families to recycle more.","The company introduced an ______ programme to reward careful work."],["onslaught","remnant","catastrophe"]],
  ["insubordinate",["Repeatedly refusing a supervisor's reasonable instruction was ______ behaviour.","The officer was disciplined for being openly ______.","A firm discussion helped the ______ employee understand the consequences of defiance."],["simultaneous","legible","prudent"]],
  ["legible",["Her handwriting was neat and completely ______.","The faded label was barely ______ after years in the sun.","Use a larger font to make the instructions ______ from a distance."],["abnormal","disputatious","prudent"]],
  ["nub",["The ______ of the issue is whether the evidence can be trusted.","Once we understood the ______ of his argument, the details made sense.","A small ______ remained where the branch had been cut."],["remnant","onslaught","incentive"]],
  ["onslaught",["The defenders prepared for an ______ from the opposing army.","The office faced an ______ of calls after the announcement.","Young plants need shelter from the winter's ______ of wind and rain."],["catastrophe","incentive","nub"]],
  ["ordain",["The ancient law appeared to ______ how land should be divided.","The church will ______ the new minister next month.","No rule can ______ that every attempt will succeed."],["evict","quench","pervade"]],
  ["outstrip",["This year's demand may ______ the available supply.","With regular training, her performance began to ______ that of her rivals.","Population growth could ______ the city's ability to build new schools."],["decrease","capsize","swerve"]],
  ["pervade",["A sense of excitement began to ______ the hall.","The aroma of spices seemed to ______ every room.","Respect should ______ all communication within the team."],["evict","ordain","quench"]],
  ["prudent",["It would be ______ to check the weather before setting out.","The committee made a ______ decision to keep emergency savings.","A ______ traveller keeps important documents in a safe place."],["disputatious","insubordinate","abnormal"]],
  ["quench",["The firefighters worked through the night to ______ the flames.","A cool drink helped ______ her thirst after the race.","The unfair rule could not ______ the students' desire to learn."],["pervade","evict","ordain"]],
  ["remnant",["A small ______ of snow remained in the shaded corner.","The museum preserves a ______ of the town's original wall.","She used a ______ piece of cloth to repair the bag."],["nub","incentive","onslaught"]],
  ["simultaneous",["The two announcements were made in ______ broadcasts.","A translator provided a ______ interpretation of the speech.","The cameras recorded the ______ arrival of both teams."],["legible","prudent","insubordinate"]],
  ["swerve",["The driver had to ______ around a fallen object.","A sudden ______ carried the bicycle toward the edge of the path.","The committee refused to ______ from its promise of fairness."],["capsize","outstrip","decrease"]]
);

audioRows.push(
  ["abnormal","","æbˈnɔːr.məl"],["capsize","","ˈkæp.saɪz"],["catastrophe","","kəˈtæs.trə.fi"],
  ["decrease","us_pron/e/eus/eus71/eus71175.mp3","n. ˈdiː.kriːs; v. dɪˈkriːs"],["disputatious","us_pron/u/usd/usdis/usdisin028.mp3","ˌdɪs.pjəˈteɪ.ʃəs"],["evict","us_pron/e/eus/eus71/eus71685.mp3","ɪˈvɪkt"],
  ["flourish","","ˈflɝː.ɪʃ"],["incentive","","ɪnˈsen.tɪv"],["insubordinate","us_pron/e/eus/eus72/eus72455.mp3","ˌɪn.səˈbɔːr.dən.ət"],
  ["legible","","ˈledʒ.ə.bəl"],["nub","us_pron/u/usn/usnub/usnub__001.mp3","nʌb"],["onslaught","us_pron/e/eus/eus75/eus75219.mp3","ˈɑːn.slɑːt"],
  ["ordain","us_pron/e/eus/eus75/eus75278.mp3","ɔːrˈdeɪn"],["outstrip","us_pron/e/eus/eus75/eus75382.mp3","ˌaʊtˈstrɪp"],["pervade","","pɚˈveɪd"],
  ["prudent","","ˈpruː.dənt"],["quench","","kwentʃ"],["remnant","","ˈrem.nənt"],
  ["simultaneous","","ˌsaɪ.məlˈteɪ.ni.əs"],["swerve","","swɝːv"]
);
