// Level B, Unit 12. Includes multiple meanings, context practice, and offline IPA.
vocabRows.push(
  [12,"abound","v.","to exist or occur in large numbers or amounts; to be plentiful.","Colourful fish abound in the protected coral reef.","flourish, teem, overflow","lack, diminish, disappear","🐟 ✨","Existing everywhere in great numbers","abound in wildlife","Abound is commonly followed by in or with: a forest abounds in wildlife; wildlife abounds in the forest."],
  [12,"braggart","n., adj.","(n.) a person who boasts loudly or often; (adj.) boastful.","The braggart talked constantly about his achievements but ignored the team's effort.","boaster, show-off, egotist","modest person, humble person","📣 🏆","Someone always boasting about himself","an arrogant braggart","Braggart is usually a noun; its less common adjective use means boastful."],
  [12,"cache","n., v.","(n.) a hidden store of supplies or valuables; stored computer data used for faster access; (v.) to hide or store for future use.","The explorers discovered a cache of emergency supplies inside the shelter.","store, reserve, stockpile; hide","exposure, shortage, discard","📦 💾","Something stored secretly or for quick use","clear the cache","Cache is pronounced like cash. In computing, cached data helps information load faster."],
  [12,"clarification","n.","an explanation or additional information that makes something clearer; the act of removing confusion.","The students requested clarification of the final assignment instructions.","explanation, interpretation, illumination","confusion, ambiguity, obscurity","💡 ❓","Extra information that removes confusion","ask for clarification","Clarification explains meaning; it does not necessarily change the original decision or instruction."],
  [12,"despondent","adj.","very discouraged, unhappy, and without hope.","The player felt despondent after the injury but recovered with support and treatment.","dejected, hopeless, disheartened","hopeful, cheerful, encouraged","🌧️ 😞","Feeling deeply discouraged and hopeless","become despondent","Despondent is stronger and more lasting than simply disappointed."],
  [12,"embezzle","v.","to steal money or property that has been entrusted to one's care, especially through a job or official position.","The accountant was accused of trying to embezzle money from the organisation.","misappropriate, steal, defraud","return, protect, reimburse","💰 🔒","Secretly stealing money placed in your care","embezzle funds","Embezzlement differs from ordinary theft because the person was trusted to manage the property."],
  [12,"heartrending","adj.","causing intense sadness, sympathy, or emotional pain.","The survivor's heartrending account moved the audience to offer help.","heartbreaking, tragic, distressing","joyful, comforting, uplifting","💔 😢","So sad that it deeply affects the heart","a heartrending story","Heartrending and heartbreaking have similar meanings; heart-rending is also written with a hyphen."],
  [12,"leisurely","adj., adv.","unhurried, relaxed, and allowing plenty of time.","The family took a leisurely walk through the park after lunch.","relaxed, unhurried, easygoing","hurried, rushed, frantic","🚶 🌤️","Moving comfortably without rushing","at a leisurely pace","Leisurely can describe a noun or modify an action: a leisurely walk; they walked leisurely."],
  [12,"lethargic","adj.","lacking energy, alertness, or enthusiasm; sluggish.","After staying awake too late, he felt lethargic during the morning lesson.","sluggish, listless, drowsy","energetic, lively, alert","🔋 😴","Having very little energy","feel lethargic","Lethargic describes unusually low energy and may have physical, emotional, or medical causes."],
  [12,"malady","n.","a disease, disorder, or illness; a serious problem affecting a person, group, or society.","Doctors worked to identify the mysterious malady affecting the village.","illness, ailment, disorder","health, wellness, cure","🩺 🤒","An illness or serious social problem","a common malady","Malady is somewhat formal and can be used literally for illness or figuratively for a harmful condition."],
  [12,"mellow","adj., v.","(adj.) pleasantly soft, smooth, rich, ripe, or relaxed; (v.) to become or make gentler, softer, or more mature.","The musician's mellow voice created a calm atmosphere.","smooth, gentle, ripe, relaxed","harsh, sharp, unripe, tense","🍑 🎵","Soft, mature, pleasant, and relaxed","a mellow tone","Mellow can describe sound, colour, flavour, fruit, mood, or a person becoming calmer with time."],
  [12,"nomadic","adj.","moving from place to place rather than living permanently in one location; relating to nomads.","The exhibit explained how nomadic communities adapted to seasonal changes.","wandering, roaming, migratory","settled, permanent, stationary","🐪 🧭","Travelling from place to place to live","a nomadic lifestyle","Nomadic describes people or groups; nomad is the corresponding noun."],
  [12,"piecemeal","adj., adv.","done, made, or happening one piece or stage at a time, often without an overall plan.","The school needed a complete repair plan rather than piecemeal changes.","gradual, fragmentary, bit by bit","complete, systematic, comprehensive","🧩 ➡️","Handling separate pieces instead of the whole","a piecemeal approach","Piecemeal may be neutral, but it often criticises an unsystematic approach."],
  [12,"quest","n., v.","(n.) a long or difficult search for something important; (v.) to search or pursue a goal.","The scientist continued her quest for a safer source of energy.","search, pursuit, mission","abandonment, retreat, surrender","🧭 ⭐","A determined search for an important goal","a quest for knowledge","Quest often suggests effort, adventure, or a goal with special importance."],
  [12,"random","adj.","chosen, done, or occurring without a definite plan, pattern, or purpose; selected so that each possibility has a fair chance.","The researcher used a random sample to reduce bias in the survey.","chance, arbitrary, haphazard","planned, deliberate, systematic","🎲 ❓","Chosen without a fixed pattern","at random","In statistics, random selection has a precise meaning and does not simply mean careless."],
  [12,"rant","v., n.","(v.) to speak or complain loudly, angrily, and at length; (n.) a long, angry speech or complaint.","The customer began to rant instead of explaining the problem calmly.","rage, rave, tirade","praise, whisper, reason","😠 📢","A long and loud angry complaint","go on a rant","A rant expresses strong emotion but often lacks calm reasoning or organisation."],
  [12,"reinforce","v.","to strengthen, support, or make more effective; to add extra people or equipment to increase strength.","Steel bars reinforce the concrete walls of the building.","strengthen, support, fortify","weaken, undermine, reduce","🧱 💪","Adding support to make something stronger","reinforce an idea","Reinforce can strengthen structures, skills, ideas, behaviour, or groups of people."],
  [12,"seclusion","n.","the state of being private, isolated, or away from other people.","The writer worked in seclusion to concentrate without interruption.","isolation, privacy, solitude","company, exposure, society","🌲 🏡","Privacy away from other people","live in seclusion","Seclusion may be chosen for peace and privacy or caused by unwanted isolation."],
  [12,"status","n.","a person's position or rank in relation to others; the present condition of something; an official or legal standing.","The website lets students check the status of their submitted assignment.","position, rank, standing; condition","insignificance, uncertainty","📊 🏅","Position, condition, or official standing","social status","Status can answer either 'What position does it have?' or 'What condition is it currently in?'"],
  [12,"turmoil","n.","a state of great confusion, disorder, uncertainty, or emotional disturbance.","Calm leadership helped the community recover from a period of turmoil.","chaos, unrest, confusion","calm, order, peace","🌪️ 🌀","Confusion and disorder affecting everything","in turmoil","Turmoil may describe public disorder or strong confusion and distress within a person." ]
);

practiceRows.push(
  ["abound",["Wildflowers ______ in the valley during spring.","Examples of geometric patterns ______ in Islamic art.","The protected wetland ______s with birds and insects."],["reinforce","mellow","rant"]],
  ["braggart",["The ______ praised himself but never thanked his teammates.","Nobody enjoyed listening to the boastful ______.","A true expert does not need to behave like a ______."],["malady","quest","status"]],
  ["cache",["The hikers found a hidden ______ of food and water.","Clearing the browser ______ may solve the loading problem.","Squirrels sometimes ______ food for later use."],["seclusion","status","quest"]],
  ["clarification",["Please ask for ______ if the instructions seem unclear.","The teacher's example provided useful ______.","A short note was added for the ______ of the new rule."],["status","turmoil","seclusion"]],
  ["despondent",["He became ______ after several unsuccessful attempts.","The injured athlete felt ______ until his recovery began.","Encouragement helped the ______ student regain hope."],["lethargic","mellow","leisurely"]],
  ["embezzle",["The manager was arrested for attempting to ______ company funds.","An employee who secretly takes entrusted money may ______ it.","Strict audits make it more difficult to ______ public funds."],["reinforce","cache","abound"]],
  ["heartrending",["The refugee's ______ account moved many people to help.","The film told a ______ story of loss and courage.","The rescue workers described a ______ scene after the disaster."],["mellow","random","leisurely"]],
  ["leisurely",["We enjoyed a ______ breakfast without watching the clock.","The visitors walked ______ through the quiet garden.","A ______ pace allowed everyone to observe the details."],["lethargic","piecemeal","random"]],
  ["lethargic",["The extreme heat made everyone feel ______.","A lack of sleep left the student slow and ______.","The normally active dog appeared unusually ______."],["leisurely","mellow","despondent"]],
  ["malady",["The doctor searched for the cause of the unusual ______.","Researchers developed a treatment for the rare ______.","The writer described corruption as a social ______."],["turmoil","status","seclusion"]],
  ["mellow",["The singer's ______ voice suited the quiet song.","Time helped the sharp cheese become more ______.","Experience had begun to ______ his impatient manner."],["heartrending","random","lethargic"]],
  ["nomadic",["The tribe followed a ______ way of life across the desert.","Some herding communities remain ______ and move with the seasons.","The museum displayed tools used by ______ peoples."],["seclusion","piecemeal","leisurely"]],
  ["piecemeal",["The building needs a complete renovation, not ______ repairs.","The information arrived ______ over several weeks.","A ______ response failed to address the whole problem."],["random","leisurely","nomadic"]],
  ["quest",["The explorers began a ______ to find the lost settlement.","Her lifelong ______ for knowledge led to many discoveries.","The hero continued to ______ for a peaceful solution."],["status","seclusion","cache"]],
  ["random",["The computer selected ten names at ______.","A ______ sample gives every member a fair chance of selection.","The scattered marks appeared to follow no pattern and seemed ______."],["piecemeal","nomadic","leisurely"]],
  ["rant",["He began to ______ angrily about the delayed service.","The speaker's long ______ offered complaints but no solution.","A calm discussion is more useful than an emotional ______."],["clarification","quest","status"]],
  ["reinforce",["Extra beams will ______ the damaged roof.","Regular practice helps ______ new vocabulary.","The commander sent more workers to ______ the emergency team."],["abound","embezzle","rant"]],
  ["seclusion",["The cabin offered complete ______ from the noisy city.","The scientist worked in ______ to protect the unfinished research.","After years of ______, the artist returned to public life."],["status","turmoil","clarification"]],
  ["status",["Students can check the ______ of their application online.","His professional ______ changed after the promotion.","The document confirmed her legal ______ as the property's owner."],["clarification","turmoil","seclusion"]],
  ["turmoil",["The sudden leadership change threw the organisation into ______.","Financial uncertainty created months of ______.","Although his thoughts were in ______, he spoke calmly."],["seclusion","status","clarification"]]
);

audioRows.push(
  ["abound","","əˈbaʊnd"],["braggart","","ˈbræɡ.ɚt"],["cache","","kæʃ"],
  ["clarification","","ˌkler.ə.fəˈkeɪ.ʃən"],["despondent","","dɪˈspɑːn.dənt"],["embezzle","","ɪmˈbez.əl"],
  ["heartrending","us_pron/u/ush/ushea/usheart008.mp3","ˈhɑːrtˌren.dɪŋ"],["leisurely","","ˈliː.ʒɚ.li"],["lethargic","","ləˈθɑːr.dʒɪk"],
  ["malady","","ˈmæl.ə.di"],["mellow","","ˈmel.oʊ"],["nomadic","","noʊˈmæd.ɪk"],
  ["piecemeal","","ˈpiːs.miːl"],["quest","","kwest"],["random","","ˈræn.dəm"],
  ["rant","","rænt"],["reinforce","","ˌriː.ɪnˈfɔːrs"],["seclusion","","sɪˈkluː.ʒən"],
  ["status","","ˈsteɪ.t̬əs"],["turmoil","","ˈtɝː.mɔɪl"]
);
