// Level B, Unit 14. Includes multiple meanings, context practice, and offline IPA.
vocabRows.push(
  [14,"affliction","n.","a condition that causes physical or mental pain, illness, hardship, or great suffering.","The medical team worked tirelessly to relieve the patient's affliction.","ailment, suffering, hardship","comfort, relief, blessing","🩹 😟","An illness or hardship that causes suffering","suffer from an affliction","Affliction may be a disease, a painful condition, or any serious source of suffering."],
  [14,"akin","adj.","similar in nature or character; related by family or origin.","The peaceful feeling was akin to the calm he experienced beside the sea.","similar, comparable, related","different, unlike, unrelated","🟰 🔗","Similar or closely related","akin to","Akin is normally followed by to, not with: this idea is akin to that one."],
  [14,"cosmopolitan","adj., n.","(adj.) including people, cultures, or influences from many countries; experienced and comfortable in many parts of the world; (n.) a cosmopolitan person.","Riyadh is becoming increasingly cosmopolitan, with residents and visitors from many countries.","international, multicultural, worldly","provincial, narrow, isolated","🌍 🏙️","Bringing together cultures from around the world","a cosmopolitan city","Cosmopolitan usually describes a diverse city or a person with broad international experience."],
  [14,"elongate","v.","to make or become longer, especially in shape or duration.","The artist used vertical lines to elongate the appearance of the room.","lengthen, extend, stretch","shorten, contract, compress","↔️ 📏","Making something longer","elongate the shape","Elongate is often used in science, design, and descriptions of physical growth or shape."],
  [14,"gala","n., adj.","(n.) a special public celebration, performance, or social event; (adj.) festive or connected with such an occasion.","The school held a gala to celebrate outstanding student achievements.","celebration, festival, special event","ordinary day, routine event","🎉 🏆","A large and special celebration","a charity gala","Gala commonly appears in phrases such as gala dinner, gala performance, and charity gala."],
  [14,"gaudy","adj.","unpleasantly bright, showy, or decorated in a way that lacks good taste.","The designer replaced the gaudy colours with a calm and balanced palette.","flashy, garish, showy","tasteful, restrained, elegant","🌈 ✨","Too bright and showy to be tasteful","gaudy decorations","Gaudy is usually negative; colourful can be positive or neutral."],
  [14,"gratitude","n.","the feeling of being thankful and appreciative for kindness, help, or benefits received.","The students expressed their gratitude to the volunteers who supported the event.","thankfulness, appreciation, recognition","ingratitude, resentment, ungratefulness","🙏 💐","A sincere feeling of thankfulness","express gratitude","Gratitude is the feeling; thanks is one way of expressing it."],
  [14,"heed","v., n.","(v.) to pay careful attention to advice, a warning, or a request; (n.) careful attention or notice.","Hikers should heed official warnings about severe weather.","notice, observe, mind","ignore, disregard, neglect","👂 ⚠️","Paying careful attention to a warning","heed the advice","Heed can be a verb or a noun: heed a warning; pay heed to a warning."],
  [14,"hoax","n., v.","(n.) a deliberate trick or false story intended to deceive people; (v.) to deceive someone with such a trick.","The alarming online message was exposed as a hoax after officials checked the facts.","fraud, deception, trick","truth, fact, genuine report","🎭 🚫","A planned trick presented as truth","an elaborate hoax","A hoax is deliberately created to deceive; an ordinary mistake is not a hoax."],
  [14,"impartial","adj.","fair and not favouring one person, group, or side over another.","An impartial judge listens carefully to evidence from both sides.","fair, unbiased, neutral","biased, prejudiced, partial","⚖️ ↔️","Fair to everyone without taking sides","an impartial decision","Impartial means free from unfair preference; it does not mean uninterested or careless."],
  [14,"impostor","n.","a person who pretends to be someone else or claims a false identity in order to deceive others.","Security officers discovered that the supposed inspector was an impostor.","fraud, pretender, impersonator","genuine person, rightful holder","🎭 🪪","Someone using a false identity","expose an impostor","Impostor refers to the deceptive person; impersonation can also be harmless when done openly for entertainment."],
  [14,"inflate","v.","to fill something with air or gas; to increase a price, number, or amount; to exaggerate the importance or value of something.","The mechanic used a pump to inflate the bicycle tyre.","expand, enlarge, exaggerate","deflate, reduce, understate","🎈 📈","Filling with air or making a value seem larger","inflate a tyre","Inflate can be literal, economic, or figurative: inflate a balloon, prices, or an achievement."],
  [14,"meager","adj.","too small in amount, quantity, quality, or strength; lacking what is needed.","The rescue team shared its meager supply of water carefully.","scanty, inadequate, sparse","abundant, plentiful, generous","🍽️ 🤏","Too small or insufficient","a meager supply","Meager, also spelled meagre in British English, suggests an amount that is disappointingly small."],
  [14,"meditate","v.","to think deeply and calmly; to focus the mind quietly for reflection, relaxation, or spiritual purposes.","Before making the difficult decision, he took time to meditate on its consequences.","reflect, contemplate, ponder","rush, disregard, ignore","🧘 💭","Thinking quietly and deeply","meditate on a question","Meditate on means think deeply about; meditate may also describe a focused reflective practice."],
  [14,"nutritious","adj.","containing substances that help the body grow, remain healthy, and produce energy.","A nutritious breakfast can help students concentrate during morning lessons.","nourishing, wholesome, healthful","unhealthy, harmful, nonnutritive","🥗 💪","Providing nutrients needed for health","a nutritious meal","Nutritious describes the food itself; nutritional relates more broadly to nutrition."],
  [14,"oppress","v.","to govern, control, or treat people in a cruel, unjust, or burdensome way; to weigh heavily on the mind or body.","Just laws should protect citizens rather than oppress them.","persecute, dominate, tyrannise","liberate, protect, free","⛓️ ⚖️","Treating people cruelly through power","oppress a population","Oppress is stronger than inconvenience and involves sustained unjust power or a heavy burden."],
  [14,"pedestrian","n., adj.","(n.) a person travelling on foot; (adj.) ordinary, dull, or lacking imagination.","The driver stopped at the crossing to allow the pedestrian to pass safely.","walker; ordinary, uninspired","driver; imaginative, remarkable","🚶 🛣️","A person walking—or something very ordinary","pedestrian crossing","The noun concerns road safety; the adjective is a critical way to call an idea or style unoriginal."],
  [14,"transmit","v.","to send or pass information, signals, energy, disease, or qualities from one person, place, or thing to another.","Satellites transmit data to receiving stations on Earth.","send, communicate, convey","receive, retain, withhold","📡 ➡️","Sending information or something else onward","transmit a signal","Transmit is used for communication, electricity, inherited traits, and the spread of infection."],
  [14,"vanquish","v.","to defeat an opponent or overcome a difficulty completely.","Through patience and practice, the athlete managed to vanquish his fear of failure.","defeat, conquer, overcome","surrender, yield, lose","🏆 🛡️","Defeating an enemy or overcoming a problem","vanquish an opponent","Vanquish is a strong, somewhat literary word suggesting a decisive victory."],
  [14,"wan","adj.","pale and appearing weak, tired, or unwell; faint or lacking brightness.","After several sleepless nights, his face looked tired and wan.","pale, weak, faint","healthy, bright, vigorous","🌙 😓","Pale, weak, and lacking brightness","a wan smile","Wan can describe a person's appearance, a weak smile, or dim light." ]
);

practiceRows.push(
  ["affliction",["The new treatment offered relief from a painful ______.","The charity supports families facing serious ______.","Drought was a continuing ______ for the farming community."],["gratitude","gala","hoax"]],
  ["akin",["The new fabric feels ______ to soft wool.","His sense of relief was ______ to freedom.","The two solutions are closely ______, although they are not identical."],["wan","gaudy","impartial"]],
  ["cosmopolitan",["The port developed into a busy, ______ city.","Its restaurants reflect the capital's ______ population.","Years of international travel gave him a ______ outlook."],["pedestrian","meager","nutritious"]],
  ["elongate",["Warm conditions cause the young plant stems to ______ quickly.","The tailor used vertical stripes to ______ the figure.","Pull both ends gently to ______ the flexible material."],["inflate","vanquish","transmit"]],
  ["gala",["The museum organised a ______ to raise money for restoration.","Guests arrived for the annual awards ______.","The orchestra prepared a special ______ performance."],["hoax","affliction","gratitude"]],
  ["gaudy",["The room's ______ decorations distracted attention from the exhibit.","He considered the extremely bright jacket too ______ for the formal event.","The advertisement used ______ colours and excessive glitter."],["wan","impartial","nutritious"]],
  ["gratitude",["We expressed our ______ to everyone who offered help.","The award was accepted with sincere ______.","A handwritten message showed the student's ______ toward his teacher."],["affliction","hoax","gala"]],
  ["heed",["Please ______ the safety instructions before using the equipment.","The driver failed to ______ the warning sign.","Wise students pay ______ to constructive advice."],["transmit","oppress","inflate"]],
  ["hoax",["Investigators proved that the frightening story was a ______.","The false competition was designed to ______ internet users.","Always check a surprising claim in case it is a ______."],["gala","affliction","impostor"]],
  ["impartial",["The referee must remain ______ throughout the match.","An ______ investigation considers evidence from every side.","Students trusted the teacher to make an ______ decision."],["akin","gaudy","wan"]],
  ["impostor",["The caller claiming to be a bank official was an ______.","Police arrested the ______ who had used a false identity.","The real doctor immediately recognised the visitor as an ______."],["hoax","pedestrian","affliction"]],
  ["inflate",["Use this pump to ______ the football.","A shortage may ______ the price of basic goods.","Do not ______ your role in the project's success."],["elongate","vanquish","transmit"]],
  ["meager",["The travellers survived on a ______ supply of food.","The worker struggled to support his family on a ______ income.","The evidence was too ______ to support the claim."],["nutritious","cosmopolitan","gaudy"]],
  ["meditate",["She found a quiet place to ______ before the busy day began.","The committee will ______ on the proposal before voting.","Take time to ______ on what you have learned."],["transmit","vanquish","oppress"]],
  ["nutritious",["Fresh vegetables are an important part of a ______ meal.","The school encourages students to choose ______ snacks.","A ______ diet supports healthy growth."],["meager","gaudy","wan"]],
  ["oppress",["A cruel ruler may use fear to ______ the population.","The law was created to protect people whom powerful groups might ______.","No government has the right to ______ peaceful citizens."],["vanquish","heed","transmit"]],
  ["pedestrian",["The ______ waited for the traffic light to change.","A raised crossing makes the road safer for each ______.","Critics found the plot predictable and ______."],["impostor","cosmopolitan","vanquish"]],
  ["transmit",["Radio towers ______ signals across long distances.","Some insects can ______ disease to humans.","The cable can ______ both power and data."],["heed","inflate","oppress"]],
  ["vanquish",["The champion trained hard to ______ his strongest rival.","The team united to ______ every obstacle before them.","The hero returned after managing to ______ the invading force."],["oppress","meditate","transmit"]],
  ["wan",["The patient looked pale and ______ after the illness.","A ______ smile appeared briefly on his tired face.","The moon gave off a ______ light through the clouds."],["gaudy","akin","impartial"]]
);

audioRows.push(
  ["affliction","","əˈflɪk.ʃən"],["akin","","əˈkɪn"],["cosmopolitan","","ˌkɑːz.məˈpɑː.lə.tən"],
  ["elongate","","ɪˈlɔːŋ.ɡeɪt"],["gala","","ˈɡeɪ.lə"],["gaudy","","ˈɡɑː.di"],
  ["gratitude","","ˈɡræt̬.ə.tuːd"],["heed","","hiːd"],["hoax","","hoʊks"],
  ["impartial","","ɪmˈpɑːr.ʃəl"],["impostor","us_pron/i/imp/impos/imposter.mp3","ɪmˈpɑː.stɚ"],["inflate","","ɪnˈfleɪt"],
  ["meager","","ˈmiː.ɡɚ"],["meditate","","ˈmed.ə.teɪt"],["nutritious","","nuːˈtrɪʃ.əs"],
  ["oppress","us_pron/e/eus/eus75/eus75248.mp3","əˈpres"],["pedestrian","","pəˈdes.tri.ən"],["transmit","","trænzˈmɪt"],
  ["vanquish","","ˈvæŋ.kwɪʃ"],["wan","","wɑːn"]
);
