// Level B, Unit 11. Includes multiple meanings, context practice, and offline IPA.
vocabRows.push(
  [11,"adequate","adj.","enough for a particular purpose or need; satisfactory but not necessarily excellent.","The emergency centre had an adequate supply of clean water.","sufficient, satisfactory, acceptable","insufficient, inadequate, deficient","✅ 📏","Enough to meet the need","adequate for the task","Adequate means enough or acceptable; it does not usually mean outstanding."],
  [11,"ajar","adj., adv.","slightly open.","He left the classroom door ajar so that fresh air could circulate.","partly open, unclosed","shut, closed, sealed","🚪 ↔️","A door opened just a little","leave the door ajar","Ajar normally follows a verb such as be, leave, or stand rather than appearing before a noun."],
  [11,"dialogue","n., v.","(n.) conversation between two or more people; spoken words in a story or play; discussion intended to solve a problem; (v.) to take part in discussion.","Respectful dialogue helped the two groups understand each other's concerns.","conversation, discussion, exchange","monologue, silence","💬 ↔️","Ideas exchanged through conversation","open a dialogue","Dialogue can be everyday conversation, written speech between characters, or formal negotiation."],
  [11,"emblem","n.","a picture, object, or design that represents an idea, quality, group, or country; a symbolic badge.","The olive branch has long been used as an emblem of peace.","symbol, badge, insignia","reality, original","🛡️ ⭐","A visible symbol representing something larger","a national emblem","An emblem represents an idea or identity and may appear on flags, uniforms, coins, or official documents."],
  [11,"gigantic","adj.","extremely large or enormous.","The museum displayed a gigantic model of a blue whale.","enormous, immense, colossal","tiny, miniature, puny","🐘 📏","Far larger than normal","a gigantic structure","Gigantic comes from giant and may describe physical size or a very large amount or effort."],
  [11,"havoc","n.","widespread destruction, damage, disorder, or confusion.","The flash flood caused havoc on roads throughout the region.","devastation, destruction, chaos","order, calm, restoration","🌪️ 💥","Serious damage and confusion spreading widely","wreak havoc","Wreak havoc is the standard expression meaning cause widespread damage or disorder."],
  [11,"hearth","n.","the floor or area in front of a fireplace; the fireplace itself; a symbol of one's home and family life.","The family gathered around the hearth during the cold evening.","fireside, fireplace, home","outdoors, wilderness","🔥 🏠","The warm centre of a fireplace or home","hearth and home","Hearth is literal near a fireplace and figurative when it represents domestic life and family."],
  [11,"implore","v.","to beg or ask someone earnestly and urgently.","The guide had to implore the visitors not to enter the unsafe area.","beg, plead, beseech","command, refuse, dismiss","🙏 💬","Begging with great urgency","implore someone to help","Implore is much stronger than ask and expresses deep urgency or emotion."],
  [11,"infamous","adj.","well known for a bad act, quality, or reputation.","The unsafe bridge became infamous for its repeated closures.","notorious, disreputable, ill-famed","honourable, respected, renowned","⚠️ 📰","Widely known for a bad reason","infamous for","Infamous is always negative; famous and renowned can describe positive reputations."],
  [11,"innumerable","adj.","too many to be counted; extremely numerous.","Innumerable stars appeared as the sky grew darker.","countless, numberless, untold","few, limited, countable","♾️ 🔢","So many that counting seems impossible","innumerable examples","Innumerable is often an exaggeration meaning a very great number, not always literally impossible to count."],
  [11,"lax","adj.","not strict, careful, or sufficiently attentive; loose or relaxed rather than firm.","Lax safety checks allowed several preventable problems to occur.","careless, negligent, lenient, loose","strict, careful, vigilant, firm","🪢 ⚠️","Rules or control that are too loose","lax supervision","Lax can describe weak discipline, careless standards, or something physically loose and relaxed."],
  [11,"mar","v.","to damage, spoil, or reduce the beauty, perfection, or success of something.","One unfair decision should not mar an otherwise successful event.","spoil, damage, blemish","improve, enhance, perfect","✨ ❌","A defect spoiling something good","mar the surface","Mar often describes damage that leaves the main thing present but less attractive or successful."],
  [11,"misdemeanor","n.","a relatively minor crime, less serious than a felony; any minor wrongdoing or misbehaviour.","The court treated the offence as a misdemeanor rather than a serious felony.","minor offence, wrongdoing, infraction","felony, virtue, good conduct","⚖️ 📄","A less serious offence","commit a misdemeanor","Misdemeanor is the American spelling; misdemeanour is the British spelling. Its exact legal meaning varies by jurisdiction."],
  [11,"mull","v., n.","(v.) to think about something carefully for some time; to heat and flavour a drink with spices; (n.) a state of confusion or deep thought.","The committee will mull the proposal before announcing its decision.","ponder, consider, reflect on","decide hastily, ignore, dismiss","🤔 🔄","Turning an idea over in your mind","mull it over","Mull over means consider carefully; mulled drinks are heated and flavoured with spices."],
  [11,"narrative","n., adj.","(n.) a spoken or written account of connected events; a story; (adj.) relating to storytelling.","The traveller's narrative described each stage of the difficult journey.","story, account, chronicle","list, statistic, silence","📖 🗣️","Events connected and told as a story","a personal narrative","A narrative may be fictional or factual and usually arranges events into a meaningful sequence."],
  [11,"overture","n.","an introductory piece of music, especially for an opera or musical; an approach, proposal, or action intended to begin friendly relations or negotiation.","The orchestra performed the overture before the curtain rose.","prelude, introduction; proposal, approach","finale, conclusion; rejection","🎼 🤝","An opening in music or friendly negotiation","make an overture","An overture begins a musical work or signals a willingness to begin communication or cooperation."],
  [11,"pact","n.","a formal agreement or promise between two or more people, groups, or countries.","The neighbouring communities formed a pact to protect the shared water supply.","agreement, treaty, covenant","disagreement, breach, conflict","🤝 📜","A serious agreement between parties","sign a pact","A pact usually involves mutual promises and is more formal than a casual arrangement."],
  [11,"stalemate","n., v.","(n.) a situation in which neither side can make progress or win; in chess, a draw when a player has no legal move but is not in check; (v.) to bring to a deadlock.","Negotiations reached a stalemate because neither side would compromise.","deadlock, impasse, standstill","breakthrough, agreement, progress","♟️ ⛔","Neither side can move forward","reach a stalemate","A chess stalemate has a precise rule; in general use it means a deadlock."],
  [11,"vindictive","adj.","having or showing a strong desire to punish someone for a real or imagined wrong; seeking revenge.","A fair leader corrects mistakes without becoming vindictive.","revengeful, spiteful, vengeful","forgiving, merciful, generous","😠 ↩️","Wanting to hurt someone in revenge","a vindictive response","Vindictive describes a desire for revenge rather than a fair effort to correct wrongdoing."],
  [11,"wilt","v., n.","(v.) to droop or become limp from heat or lack of water; to lose energy, courage, or confidence; (n.) the process of wilting or a plant disease that causes it.","The leaves began to wilt in the afternoon heat.","droop, wither, weaken","revive, flourish, strengthen","🌿 ☀️","Losing firmness, freshness, or confidence","wilt in the heat","Wilt can describe plants literally and people figuratively when their energy or confidence fades." ]
);

practiceRows.push(
  ["adequate",["The shelter had ______ space for every family.","Her explanation was ______, although more detail would improve it.","Check that the batteries provide ______ power for the device."],["gigantic","lax","innumerable"]],
  ["ajar",["The window stood ______, allowing a cool breeze inside.","Please leave the door ______ rather than closing it completely.","He noticed that the cabinet was slightly ______."],["lax","adequate","gigantic"]],
  ["dialogue",["The characters' ______ revealed their different opinions.","Peaceful ______ may help both groups reach an agreement.","The teacher asked students to write a short ______ between two travellers."],["narrative","overture","pact"]],
  ["emblem",["The eagle appears as an ______ on the official seal.","The red crescent is recognised as an ______ of humanitarian assistance.","The team selected a tree as its ______ of strength and growth."],["narrative","hearth","pact"]],
  ["gigantic",["A ______ crane lifted the heavy section into place.","The telescope captured an image of a ______ cloud of gas in space.","Completing the archive was a ______ task requiring many volunteers."],["adequate","lax","ajar"]],
  ["havoc",["The violent storm caused ______ across the coastal town.","A computer virus could wreak ______ on an unprotected network.","The sudden power failure created ______ during the crowded event."],["stalemate","dialogue","pact"]],
  ["hearth",["The cat slept beside the warm ______.","A stone ______ stood in front of the fireplace.","The poem uses the ______ as a symbol of family and home."],["pact","emblem","overture"]],
  ["implore",["Residents had to ______ the council to repair the dangerous road.","I ______ you to consider the consequences before acting.","The lost traveller began to ______ the guide for help."],["mull","mar","wilt"]],
  ["infamous",["The abandoned road was ______ for accidents during storms.","The dishonest official became ______ throughout the region.","The prison was once ______ for its harsh conditions."],["vindictive","adequate","gigantic"]],
  ["innumerable",["The library offered ______ possibilities for independent learning.","______ grains of sand covered the beach.","The scientist answered ______ questions during his long career."],["gigantic","adequate","lax"]],
  ["lax",["______ enforcement of the rules led to repeated safety problems.","The editor's ______ attention allowed several errors to remain.","The rope became ______ and needed to be tightened."],["adequate","ajar","gigantic"]],
  ["mar",["A deep scratch could ______ the polished surface.","The argument did not ______ the success of the celebration.","One inaccurate paragraph may ______ an otherwise excellent report."],["mull","implore","wilt"]],
  ["misdemeanor",["The law classified the minor offence as a ______.","The defendant was charged with a ______ rather than a felony.","Even a small ______ may have legal consequences."],["pact","emblem","narrative"]],
  ["mull",["Take a day to ______ the offer before replying.","The panel continued to ______ over the difficult question.","She wanted time to ______ each possible solution."],["mar","implore","wilt"]],
  ["narrative",["His travel ______ followed the journey from beginning to end.","The author changed the ______ viewpoint in the final chapter.","A clear ______ connects separate events into a meaningful story."],["dialogue","emblem","pact"]],
  ["overture",["The opera began with a dramatic ______.","The ambassador made a peaceful ______ to restart negotiations.","The short orchestral ______ introduced melodies heard later in the musical."],["narrative","pact","hearth"]],
  ["pact",["The two clubs made a ______ to share their equipment.","Both countries promised to honour the peace ______.","Their ______ required each member to protect the environment."],["dialogue","emblem","narrative"]],
  ["stalemate",["The chess game ended in a ______.","Talks reached a ______ when neither side would change its position.","A compromise finally broke the political ______."],["havoc","dialogue","overture"]],
  ["vindictive",["The manager remained fair instead of becoming ______ toward his critics.","A ______ person may seek punishment simply for revenge.","His ______ message was intended to hurt someone who had disagreed with him."],["infamous","adequate","lax"]],
  ["wilt",["The flowers will ______ without enough water.","The exhausted players began to ______ in the intense heat.","His confidence seemed to ______ under constant unfair criticism."],["mar","mull","implore"]]
);

audioRows.push(
  ["adequate","","ˈæd.ə.kwət"],["ajar","","əˈdʒɑːr"],["dialogue","","ˈdaɪ.ə.lɑːɡ"],
  ["emblem","","ˈem.bləm"],["gigantic","","dʒaɪˈɡæn.tɪk"],["havoc","","ˈhæv.ək"],
  ["hearth","","hɑːrθ"],["implore","","ɪmˈplɔːr"],["infamous","","ˈɪn.fə.məs"],
  ["innumerable","","ɪˈnuː.mɚ.ə.bəl"],["lax","","læks"],["mar","","mɑːr"],
  ["misdemeanor","","ˌmɪs.dɪˈmiː.nɚ"],["mull","us_pron/u/usm/usmuc/usmucku013.mp3","mʌl"],["narrative","","ˈner.ə.t̬ɪv"],
  ["overture","us_pron/e/eus/eus75/eus75445.mp3","ˈoʊ.vɚ.tʃɚ"],["pact","us_pron/p/pac/packe/packed.mp3","pækt"],["stalemate","","ˈsteɪl.meɪt"],
  ["vindictive","","vɪnˈdɪk.tɪv"],["wilt","","wɪlt"]
);
