// Level B, Unit 9. Includes multiple meanings, context practice, and offline IPA.
vocabRows.push(
  [9,"accelerate","v.","to move faster; to cause something to move, happen, or develop more quickly.","The new reading routine helped accelerate the students' progress.","speed up, hasten, quicken","slow, delay, decelerate","🏎️ 💨","Moving or developing faster","accelerate rapidly","Accelerate can describe physical speed or any process whose rate increases."],
  [9,"bystander","n.","a person who is present at an event but does not take part in it.","A responsible bystander called for help when he saw the accident.","onlooker, observer, spectator","participant, helper, actor","👀 🚶","Someone watching without participating","an innocent bystander","A bystander is nearby but not directly involved; a witness may also provide evidence about what happened."],
  [9,"canvass","v., n.","(v.) to ask people for votes, opinions, or support; to discuss or examine thoroughly; (n.) an organised effort to gather support or opinions.","The student council members will canvass their classmates before making a decision.","survey, poll, solicit, examine","ignore, overlook, disregard","🗳️ 📝","Asking many people for opinions or support","canvass voters","Do not confuse canvass with canvas, the strong cloth used for tents and paintings."],
  [9,"casual","adj., n.","(adj.) relaxed or informal; happening by chance; showing little concern; temporary or irregular; (n.) a temporary worker.","The school allowed casual clothing during the weekend activity.","informal, relaxed, chance, temporary","formal, deliberate, permanent, concerned","👕 🙂","Relaxed, informal, or not permanent","casual conversation","Casual has several meanings, so the surrounding context is important."],
  [9,"downtrodden","adj., n.","(adj.) treated unfairly, oppressed, or made powerless; (n.) people who are oppressed or badly treated.","The organisation provided legal support for downtrodden workers.","oppressed, mistreated, powerless","privileged, powerful, respected","⬇️ 😔","People unfairly pushed down by others","help the downtrodden","Downtrodden is usually used figuratively for people suffering long-term unfair treatment."],
  [9,"entice","v.","to attract or persuade someone by offering pleasure, advantage, or reward.","The colourful book display may entice younger readers to explore a new story.","tempt, attract, lure","repel, discourage, deter","🧲 🎁","Drawing someone toward an appealing offer","entice someone to try","Entice can be positive or negative depending on what is offered and why."],
  [9,"erode","v.","to wear away gradually; to weaken or destroy something little by little.","Waves slowly erode the rocks along the coast.","wear away, corrode, weaken","build, strengthen, restore","🌊 🪨","Gradual wearing away or weakening","erode confidence","Erode can describe physical surfaces or abstract things such as trust, rights, and confidence."],
  [9,"flounder","v., n.","(v.) to struggle clumsily, move awkwardly, or have serious difficulty; (n.) a flat sea fish.","Without clear instructions, the new team began to flounder.","struggle, stumble, thrash","succeed, progress, thrive","🐟 🌊","Struggling without control or direction","flounder helplessly","As a verb, flounder means struggle; as a noun, it names a type of flatfish."],
  [9,"graphic","adj., n.","(adj.) shown through pictures or diagrams; vividly and clearly described, sometimes with disturbing detail; (n.) a picture, diagram, or visual design.","The teacher used a graphic to explain how the water cycle works.","visual, pictorial, vivid, explicit","vague, unclear, understated","🖼️ 📊","A visual display or especially vivid description","graphic design","Graphic may mean visual, vividly detailed, or a visual image such as a chart."],
  [9,"gruesome","adj.","causing horror, shock, or disgust because it is extremely unpleasant or violent.","The documentary avoided showing gruesome details of the disaster.","horrifying, ghastly, grisly","pleasant, comforting, delightful","⚠️ 😨","Something horrifying and difficult to look at","a gruesome scene","Gruesome is a strong word and should not be used merely for something slightly unpleasant."],
  [9,"melancholy","n., adj.","(n.) a deep, quiet, or lasting sadness; (adj.) deeply or thoughtfully sad.","A feeling of melancholy filled him when the long journey ended.","sadness, sorrow, gloom","joy, cheerfulness, delight","🌧️ 😔","A quiet and thoughtful sadness","a melancholy mood","Melancholy can name the feeling or describe a sad mood, sound, or scene."],
  [9,"ordeal","n.","a very painful, difficult, frightening, or exhausting experience; historically, a severe test used to decide guilt or innocence.","The passengers remained calm throughout the long rescue ordeal.","trial, hardship, suffering","comfort, pleasure, ease","🧗 ⏳","A long and difficult experience","go through an ordeal","In modern use, ordeal usually means a severe experience rather than an ordinary challenge."],
  [9,"parch","v.","to make extremely dry or thirsty, especially through heat; to become very dry.","The intense afternoon sun began to parch the unwatered soil.","dry, dehydrate, scorch","soak, moisten, refresh","☀️ 🏜️","Heat removing nearly all moisture","parched with thirst","Parched commonly describes dry land, a dry mouth, or someone who is extremely thirsty."],
  [9,"persist","v.","to continue firmly despite difficulty or opposition; to continue to exist or remain.","If you persist with daily practice, your fluency will improve.","continue, persevere, endure","quit, cease, abandon","🔁 💪","Continuing despite difficulty","persist in trying","Persist may describe determined action or a condition that continues to exist."],
  [9,"puny","adj.","very small, weak, or less impressive than expected.","The puny plant grew stronger after receiving enough light and water.","tiny, weak, undersized","large, strong, powerful","🌱 🔍","Unusually small or weak","a puny effort","Puny often expresses disapproval and can sound insulting when used about a person."],
  [9,"quibble","v., n.","(v.) to argue or complain about a small, unimportant detail; (n.) a minor objection or criticism.","The committee should decide the main issue rather than quibble over one word.","nitpick, object, cavil","agree, accept, approve","💬 🔎","Arguing about a tiny detail","quibble over details","A quibble focuses on a minor point and may distract from the main issue."],
  [9,"ratify","v.","to approve formally and make an agreement, decision, or treaty officially valid.","Each member country must ratify the agreement before it becomes binding.","approve, confirm, endorse","reject, cancel, veto","✅ 📜","Giving formal approval","ratify an agreement","People may agree informally first; ratification makes the decision official."],
  [9,"regal","adj.","royal; suitable for or resembling a king or queen in dignity, appearance, or manner.","The eagle's calm, powerful pose gave it a regal appearance.","royal, majestic, stately","common, humble, undignified","👑 🏰","Having the dignity or splendour of royalty","a regal bearing","Regal may describe actual royalty or anything that appears majestic and dignified."],
  [9,"stifle","v.","to make breathing difficult or suffocate; to hold back, suppress, or prevent something from developing.","Fear of mistakes should never stifle a student's curiosity.","suppress, restrain, smother","encourage, release, express","🤐 🌱","Holding something back or stopping its growth","stifle a laugh","Stifle may refer to breathing, emotions, sounds, ideas, creativity, or growth."],
  [9,"vital","adj., n.","(adj.) absolutely necessary or essential; full of life and energy; relating to life or the body's essential functions; (n., usually plural) the body's vital signs or organs.","Clean water is vital to the health of every community.","essential, crucial, lively","unimportant, unnecessary, lifeless","❤️ ⚡","Essential to life or success","a vital role","Vital can mean necessary, energetic, or connected with the maintenance of life." ]
);

practiceRows.push(
  ["accelerate",["Pressing the pedal caused the car to ______ smoothly.","New technology may ______ the process of analysing the results.","The falling object continued to ______ as gravity pulled it downward."],["persist","stifle","erode"]],
  ["bystander",["A nearby ______ described the accident to the police.","The trained ______ stepped forward to call emergency services.","Although he was only a ______, he noticed an important detail."],["canvass","casual","ordeal"]],
  ["canvass",["Volunteers will ______ residents to learn their opinions about the park.","Candidates often ______ neighbourhoods before an election.","The panel met to ______ every possible solution thoroughly."],["quibble","ratify","entice"]],
  ["casual",["He wore ______ clothes to the informal weekend meeting.","A ______ remark can still hurt someone even when no harm was intended.","The restaurant hired extra ______ workers during the busy season."],["regal","vital","graphic"]],
  ["downtrodden",["The charity defended people who had been ______ and ignored.","The novel describes how the ______ struggled against unfair treatment.","A fair society should protect its most ______ members."],["regal","casual","vital"]],
  ["entice",["The bakery's pleasant smell may ______ customers inside.","A reward can ______ students to try an unfamiliar book.","Dishonest advertisements sometimes ______ buyers with promises they cannot keep."],["stifle","erode","ratify"]],
  ["erode",["Heavy rain can slowly ______ unprotected soil.","Repeated dishonesty will ______ people's trust.","Salt water began to ______ the exposed metal surface."],["accelerate","persist","parch"]],
  ["flounder",["The swimmer began to ______ in the rough current.","Without a clear plan, the project continued to ______.","The speaker started to ______ when asked questions he had not prepared for."],["persist","accelerate","stifle"]],
  ["graphic",["The report included a ______ showing changes in rainfall.","Her ______ description made the distant landscape easy to imagine.","Students created a simple ______ to present the survey results."],["gruesome","casual","regal"]],
  ["gruesome",["The news report warned viewers before describing the ______ discovery.","The director suggested violence without showing ______ images.","The old tale contained a ______ scene that frightened many readers."],["graphic","melancholy","puny"]],
  ["melancholy",["The slow music created a ______ atmosphere.","He felt a quiet ______ when his friends departed.","A ______ expression crossed the traveller's face as he remembered home."],["regal","casual","vital"]],
  ["ordeal",["Being lost overnight in the desert was a frightening ______.","The rescued hikers described their experience as a long ______.","Support from family helped him through the difficult ______."],["bystander","quibble","canvass"]],
  ["parch",["Hot, dry winds can ______ the land within days.","Hours without water began to ______ the travellers' throats.","The fierce sun will ______ these leaves unless we water them."],["erode","stifle","accelerate"]],
  ["persist",["You must ______ even when the first solution fails.","If the symptoms ______, a doctor should be consulted.","The determined researcher continued to ______ with the difficult experiment."],["flounder","stifle","accelerate"]],
  ["puny",["The kitten looked ______ beside the enormous dog.","A ______ flashlight was not strong enough to light the large cave.","The seedling remained ______ until it received better soil."],["regal","vital","gruesome"]],
  ["quibble",["Do not ______ about the colour when the safety problem is more important.","Her only ______ concerned a minor change in punctuation.","They began to ______ over who should write the final sentence."],["canvass","ratify","entice"]],
  ["ratify",["The council voted to ______ the new agreement.","The treaty will not take effect until both countries ______ it.","Members gathered to ______ the decision formally."],["canvass","quibble","entice"]],
  ["regal",["The actor entered with a proud and ______ bearing.","Tall columns gave the building a ______ appearance.","The lion's calm posture looked almost ______."],["puny","casual","melancholy"]],
  ["stifle",["Covering the fire completely may ______ the flames.","The strict atmosphere began to ______ creative ideas.","He tried to ______ a laugh during the serious announcement."],["entice","persist","accelerate"]],
  ["vital",["Accurate information is ______ during an emergency.","Sleep plays a ______ role in healthy development.","The energetic speaker brought a ______ spirit to the campaign."],["casual","puny","melancholy"]]
);

audioRows.push(
  ["accelerate","","əkˈsel.ə.reɪt"],["bystander","","ˈbaɪˌstæn.dɚ"],["canvass","us_pron/c/can/canva/canvas.mp3","ˈkæn.vəs"],
  ["casual","","ˈkæʒ.u.əl"],["downtrodden","us_pron/u/usd/usdow/usdownt001.mp3","ˈdaʊnˌtrɑː.dən"],["entice","","ɪnˈtaɪs"],
  ["erode","","ɪˈroʊd"],["flounder","","ˈflaʊn.dɚ"],["graphic","","ˈɡræf.ɪk"],
  ["gruesome","","ˈɡruː.səm"],["melancholy","","ˈmel.ən.kɑː.li"],["ordeal","us_pron/e/eus/eus75/eus75279.mp3","ɔːrˈdiːl"],
  ["parch","us_pron/c/cdo/cdo03/cdo0318usparc3551.mp3","pɑːrtʃ"],["persist","","pɚˈsɪst"],["puny","","ˈpjuː.ni"],
  ["quibble","","ˈkwɪb.əl"],["ratify","","ˈræt̬.ə.faɪ"],["regal","","ˈriː.ɡəl"],
  ["stifle","","ˈstaɪ.fəl"],["vital","","ˈvaɪ.t̬əl"]
);
