// Level B, Unit 13. Includes multiple meanings, context practice, and offline IPA.
vocabRows.push(
  [13,"agitation","n.","a state of nervousness, excitement, or disturbance; forceful public action supporting or opposing change; the act of stirring or shaking something.","His visible agitation decreased when the missing document was found.","anxiety, disturbance, unrest","calm, composure, tranquillity","😟 🌊","Nervousness or restless disturbance","show signs of agitation","Agitation may describe emotional uneasiness, social unrest, or physical stirring."],
  [13,"blurt","v.","to say something suddenly and without thinking, especially something that should have remained secret.","In his excitement, Sami began to blurt out the surprise announcement.","exclaim, disclose, let slip","conceal, suppress, withhold","🗯️ 😮","Speaking suddenly before thinking","blurt out the answer","Blurt is commonly followed by out: blurt out a secret or blurt something out."],
  [13,"chronological","adj.","arranged in the order in which events happened or according to time.","The historian presented the ruler's achievements in chronological order.","sequential, time-ordered, consecutive","random, unordered, jumbled","📅 ➡️","Events arranged from earlier to later","chronological order","Chronological order follows time; it does not necessarily rank events by importance."],
  [13,"countenance","n., v.","(n.) a person's face or facial expression; (v.) to accept, approve of, or tolerate something.","The principal would not countenance dishonest behaviour from any student.","face, expression; tolerate, permit","disapprove, forbid, reject","🙂 🚫","A facial expression—or permitting something","a cheerful countenance","The noun is formal for face or expression; the verb usually appears in negative statements about unacceptable conduct."],
  [13,"diminish","v.","to make or become smaller, weaker, less important, or less valuable.","The pain began to diminish after the patient received treatment.","decrease, lessen, reduce","increase, enlarge, intensify","📉 🔉","Becoming smaller or less powerful","diminish in importance","Diminish can be transitive or intransitive: something diminishes, or one thing diminishes another."],
  [13,"enchant","v.","to delight or attract someone greatly; to place under a magical spell.","The storyteller's vivid description seemed to enchant the young audience.","delight, captivate, charm","bore, repel, disenchant","✨ 🪄","Delighting someone as if by magic","enchant the audience","Enchant is often figurative, meaning to charm deeply rather than literally use magic."],
  [13,"fluctuate","v.","to rise and fall or change irregularly in level, amount, value, or strength.","Temperatures fluctuate considerably between day and night in the desert.","vary, shift, oscillate","stabilise, remain, settle","📈 📉","Moving repeatedly up and down","prices fluctuate","Fluctuate describes repeated variation, not one simple increase or decrease."],
  [13,"foster","v., adj.","(v.) to encourage the growth or development of something; to care for a child temporarily; (adj.) providing or receiving temporary family care.","Collaborative projects foster respect and responsibility among students.","encourage, promote, nurture","discourage, hinder, suppress","🌱 🤝","Helping growth through care and support","foster cooperation","Foster can refer to developing an idea or quality, as well as temporary care for a child."],
  [13,"grovel","v.","to lie or crawl close to the ground; to behave with excessive humility or submission in order to gain favour or forgiveness.","The honest employee apologised sincerely but refused to grovel before the manager.","crawl, cringe, abase oneself","stand tall, resist, defy","🙇 ⬇️","Acting excessively humble or submissive","grovel for forgiveness","In figurative use, grovel is disapproving and suggests loss of dignity."],
  [13,"handicraft","n.","an object made skilfully by hand; the activity or skill of making decorative or useful objects by hand.","The market displayed traditional Saudi handicraft made from palm leaves.","craft, handiwork, handwork","mass production, machine-made goods","🧺 👐","A useful or decorative object made by hand","traditional handicraft","Handicraft may refer to the skill or activity in general or to an individual handmade item."],
  [13,"hilarious","adj.","extremely funny or causing great amusement.","The actor's harmless imitation was so hilarious that the audience could not stop laughing.","very funny, amusing, comical","serious, dull, humourless","😂 🎭","Extremely funny","a hilarious story","Hilarious is stronger than funny and should be reserved for something that causes great laughter."],
  [13,"ignite","v.","to catch fire or cause something to burn; to cause a strong feeling, interest, or conflict to begin.","The science demonstration helped ignite the students' curiosity about energy.","kindle, light, spark","extinguish, quench, suppress","🔥 💡","Starting a flame or powerful feeling","ignite interest","Ignite may describe literal fire or figuratively starting enthusiasm, debate, or conflict."],
  [13,"magnitude","n.","great size, extent, or importance; a numerical measure of the strength of an earthquake, star, or other quantity.","The relief team quickly understood the magnitude of the damage.","scale, extent, importance","smallness, insignificance, triviality","📏 🌍","The great size or seriousness of something","the magnitude of the problem","Magnitude often stresses how large or serious something is and also has precise scientific meanings."],
  [13,"massive","adj.","very large, heavy, solid, extensive, or serious.","Engineers designed massive supports to carry the weight of the bridge.","enormous, immense, substantial","tiny, slight, miniature","🏗️ 🐘","Extremely large and heavy","a massive structure","Massive can describe physical size or a figuratively great amount, effect, or effort."],
  [13,"maternal","adj.","relating to a mother; showing the affection, protection, or care associated with a mother.","The nurse spoke to the frightened child in a warm, maternal manner.","motherly, caring, protective","paternal, uncaring, neglectful","🤱 💗","Relating to a mother's care","maternal instinct","Maternal refers to the mother’s side or motherlike qualities; paternal refers to the father’s side."],
  [13,"pall","n., v.","(n.) a dark covering or an atmosphere of sadness or gloom; (v.) to become less interesting or enjoyable through familiarity.","A pall of smoke hung over the area after the warehouse fire.","gloom, shadow, cloud; weary","brightness, cheer, delight","🌫️ 😔","A gloomy covering or loss of interest","cast a pall over","As a noun, pall often appears in cast a pall over; as a verb, an experience may pall after too much repetition."],
  [13,"reputable","adj.","having a good reputation and generally respected, trusted, or considered reliable.","The family selected a reputable company with a record of safe construction.","respected, trustworthy, reliable","disreputable, dishonest, unreliable","⭐ ✅","Known and trusted for good quality","a reputable source","Reputable describes someone or something with an established good reputation."],
  [13,"revere","v.","to feel or show deep respect and admiration for someone or something.","Muslims revere the Qur'an as the holy book of Islam.","respect, honour, venerate","despise, scorn, dishonour","📖 🤲","Showing profound respect and honour","revere a wise leader","Revere expresses deeper respect than admire and is often used for sacred things or highly respected people."],
  [13,"saga","n.","a long story about heroic events or a family over generations; a long, complicated series of events.","The novel follows a family saga across three generations.","epic, chronicle, long tale","short story, episode, fragment","📚 🛡️","A long story spanning many events","a family saga","Saga originally referred to medieval Norse narratives and now also describes any lengthy, complicated story."],
  [13,"stodgy","adj.","dull, old-fashioned, and uninteresting; heavy and filling as food; thick or solid in texture.","The designer transformed the stodgy report into a clear and engaging presentation.","dull, stuffy, heavy","lively, modern, light","🥣 🥱","Heavy, dull, or old-fashioned","stodgy food","Stodgy may criticise ideas or style as dull, or describe food that is heavy and filling." ]
);

practiceRows.push(
  ["agitation",["His restless movements revealed his ______.","The announcement caused public ______ throughout the city.","Gentle ______ keeps the ingredients evenly mixed."],["magnitude","handicraft","reputable"]],
  ["blurt",["Do not ______ out the answer before everyone has time to think.","Nervousness caused him to ______ the secret.","She covered her mouth after she began to ______ out the surprise."],["grovel","revere","fluctuate"]],
  ["chronological",["Arrange the historical events in ______ order.","The biography gives a ______ account from childhood to old age.","A timeline presents information in a ______ sequence."],["massive","maternal","reputable"]],
  ["countenance",["The coach would not ______ cheating under any circumstances.","A smile brightened the visitor's ______.","The committee refused to ______ disrespectful conduct."],["foster","diminish","enchant"]],
  ["diminish",["The noise began to ______ as the crowd moved away.","Regular maintenance can ______ the risk of breakdowns.","One mistake does not ______ the value of all your hard work."],["ignite","fluctuate","foster"]],
  ["enchant",["The beautiful recitation seemed to ______ the listeners.","Colourful lights ______ visitors during the festival.","The imaginative tale will ______ young readers."],["diminish","grovel","blurt"]],
  ["fluctuate",["Fuel prices may ______ from one month to another.","His energy levels ______ depending on how well he sleeps.","The graph shows that temperatures ______ throughout the year."],["diminish","ignite","foster"]],
  ["foster",["Team activities ______ cooperation among students.","The programme was created to ______ creativity and confidence.","A supportive classroom can ______ a love of reading."],["diminish","countenance","ignite"]],
  ["grovel",["He would apologise honestly, but he would not ______ for approval.","The defeated servant was forced to ______ before the cruel ruler.","You should accept responsibility without having to ______."],["blurt","revere","enchant"]],
  ["handicraft",["The artisan sold a beautiful wooden ______ at the market.","Basket weaving is a traditional ______ in the region.","Each ______ showed the maker's patience and skill."],["saga","countenance","magnitude"]],
  ["hilarious",["The comedian's final story was absolutely ______.","We watched a ______ scene that made everyone laugh.","His harmless misunderstanding was so ______ that we remembered it for years."],["stodgy","maternal","chronological"]],
  ["ignite",["A single spark can ______ dry grass.","The teacher's question helped ______ a lively debate.","The discovery may ______ new interest in the ancient site."],["diminish","foster","fluctuate"]],
  ["magnitude",["Scientists measured the ______ of the earthquake.","We did not understand the ______ of the challenge at first.","The map revealed the true ______ of the flooded area."],["agitation","handicraft","countenance"]],
  ["massive",["A ______ stone gate stood at the entrance.","The rescue operation required a ______ amount of equipment.","The company suffered a ______ loss after the storm."],["stodgy","maternal","reputable"]],
  ["maternal",["The patient knew little about his ______ family history.","Her ______ kindness reassured the lost child.","The young animals depended on ______ care."],["massive","chronological","hilarious"]],
  ["pall",["Dark clouds cast a ______ over the afternoon celebration.","A ______ of silence fell over the room after the sad news.","After many repetitions, the once-exciting routine began to ______."],["saga","magnitude","handicraft"]],
  ["reputable",["Use information from a ______ scientific source.","They hired a ______ electrician recommended by several neighbours.","A ______ charity explains clearly how donations are used."],["stodgy","massive","maternal"]],
  ["revere",["The community continues to ______ the scholar for his wisdom.","Many cultures ______ their ancestors and preserve their stories.","Students should ______ truth and honest scholarship."],["grovel","blurt","countenance"]],
  ["saga",["The film tells an epic ______ of courage and survival.","The legal ______ continued for several years.","Our grandfather recorded the family's ______ for future generations."],["pall","handicraft","agitation"]],
  ["stodgy",["The editor replaced the ______ language with a lively style.","The restaurant was known for heavy, ______ meals.","Their once-modern office now looked formal and ______."],["hilarious","reputable","chronological"]]
);

audioRows.push(
  ["agitation","","ˌædʒ.əˈteɪ.ʃən"],["blurt","us_pron/u/usc/uscld/uscld00103.mp3","blɝːt"],["chronological","","ˌkrɑː.nəˈlɑː.dʒɪ.kəl"],
  ["countenance","","ˈkaʊn.t̬ən.əns"],["diminish","","dɪˈmɪn.ɪʃ"],["enchant","us_pron/e/eus/eus75/eus75684.mp3","ɪnˈtʃænt"],
  ["fluctuate","","ˈflʌk.tʃu.eɪt"],["foster","","ˈfɑː.stɚ"],["grovel","","ˈɡrɑː.vəl"],
  ["handicraft","us_pron/u/ush/usham/ushamha012.mp3","ˈhæn.di.kræft"],["hilarious","us_pron/e/eus/eus72/eus72219.mp3","hɪˈler.i.əs"],["ignite","","ɪɡˈnaɪt"],
  ["magnitude","","ˈmæɡ.nə.tuːd"],["massive","","ˈmæs.ɪv"],["maternal","","məˈtɝː.nəl"],
  ["pall","","pɔːl"],["reputable","","ˈrep.jə.t̬ə.bəl"],["revere","","rɪˈvɪr"],
  ["saga","","ˈsɑː.ɡə"],["stodgy","","ˈstɑː.dʒi"]
);
