// Level B, Unit 15. Includes multiple meanings, context practice, and offline IPA.
vocabRows.push(
  [15,"authoritative","adj.","reliable and accepted as accurate because it comes from an expert or official source; confident, commanding, and likely to be obeyed.","The students used an authoritative dictionary to verify the word's meaning.","reliable, official, commanding","unreliable, unofficial, hesitant","📚 ✅","Trusted as accurate or confidently commanding","an authoritative source","Authoritative may describe trustworthy information or a person's confident manner; authoritarian means demanding strict obedience."],
  [15,"bankrupt","adj., n., v.","(adj.) legally unable to pay debts; completely lacking a valuable quality; (n.) a bankrupt person or organisation; (v.) to cause financial ruin.","Poor planning and heavy debt left the company bankrupt.","insolvent, ruined, depleted","solvent, prosperous, wealthy","🏦 📉","Unable to pay debts or completely lacking something","go bankrupt","Bankrupt has a precise financial meaning but may also be figurative, as in morally bankrupt."],
  [15,"clamor","n., v.","(n.) a loud, confused noise or forceful public demand; (v.) to shout loudly or demand something insistently.","A clamor of excited voices filled the hall after the results were announced.","uproar, outcry, demand","silence, quiet, calm","📣 🔊","A loud noise or insistent demand","clamor for change","Clamor is the American spelling; clamour is standard in British English."],
  [15,"coincide","v.","to happen at the same time or occupy the same position; to agree exactly or be consistent.","The school celebration will coincide with the national holiday.","occur together, correspond, agree","differ, conflict, diverge","📅 🟰","Happening together or matching exactly","coincide with","Coincide is normally followed by with: the dates coincide with each other; their opinions coincide."],
  [15,"cynical","adj.","distrustful of people's motives and believing that they usually act for selfish reasons; doubtful or scornful about sincerity.","The volunteer remained hopeful despite the cynical comments about his efforts.","distrustful, sceptical, pessimistic","trusting, idealistic, optimistic","🤨 🌧️","Doubting that people have sincere motives","a cynical remark","Cynical questions sincerity; sceptical more neutrally means not easily convinced."],
  [15,"despot","n.","a ruler or other person who holds great power and uses it in a cruel, oppressive, or unfair way.","The despot silenced peaceful criticism and ruled through fear.","tyrant, dictator, oppressor","liberator, democrat, protector","👑 ⛓️","A ruler who uses absolute power cruelly","a ruthless despot","Despot is strongly negative and focuses on the abusive use of unchecked power."],
  [15,"feud","n., v.","(n.) a long and bitter quarrel between people, families, or groups; (v.) to remain involved in such a quarrel.","The community elders helped the two families end their long feud peacefully.","conflict, rivalry, vendetta","peace, harmony, reconciliation","⚔️ 🤝","A bitter quarrel lasting a long time","a family feud","A feud continues over time and often involves repeated acts of hostility, unlike a brief disagreement."],
  [15,"haggle","v., n.","(v.) to argue about a price or terms in order to reach a better agreement; (n.) an act or period of bargaining.","The customer and merchant began to haggle politely over the carpet's price.","bargain, negotiate, barter","accept, agree, concede","💰 ↔️","Negotiating repeatedly over a price","haggle over the price","Haggle often concerns price, while negotiate can concern any terms or agreement."],
  [15,"hardy","adj.","strong, healthy, and able to survive difficult conditions; describing a plant that can withstand cold or harsh weather.","The hardy desert plant survives with very little water.","robust, tough, resilient","fragile, delicate, weak","🌵 💪","Strong enough to survive harsh conditions","a hardy plant","Hardy describes physical toughness or survival; hearty commonly means warm, enthusiastic, or substantial."],
  [15,"harmonious","adj.","friendly, peaceful, and free from disagreement; forming a pleasing and well-balanced combination of sounds, colours, or parts.","Respectful discussion helped the group maintain a harmonious relationship.","peaceful, agreeable, balanced","hostile, discordant, conflicting","🎶 🤝","Peaceful together or pleasingly balanced","a harmonious relationship","Harmonious can describe social agreement or elements that combine attractively."],
  [15,"hoard","n., v.","(n.) a hidden or carefully stored supply of valuable objects or goods; (v.) to collect and keep an excessive amount, often secretly.","Archaeologists uncovered a hoard of ancient coins beneath the floor.","stockpile, store, cache","distribute, share, disperse","📦 🔒","A stored collection kept for future use","hoard supplies","Hoard is a stored collection; horde, which sounds the same, means a large crowd or group."],
  [15,"indisposed","adj.","slightly ill or unwell; unwilling or not inclined to do something.","The speaker was indisposed, so the lecture was postponed.","unwell, ailing; unwilling","healthy, well; willing","🤒 🚫","Unwell—or unwilling to act","feel indisposed","Indisposed is a polite, formal way to say slightly ill; indisposed to means unwilling."],
  [15,"legacy","n.","money or property left to someone in a will; something valuable or harmful passed down from the past; a lasting influence or result.","The scholar's legacy continues through the students he inspired.","inheritance, heritage, lasting impact","loss, disappearance, oblivion","🏛️ 🌱","Something passed down or remembered afterward","leave a legacy","Legacy can be personal, cultural, financial, or technical, as in a legacy computer system."],
  [15,"legitimate","adj.","lawful and permitted by rules; genuine rather than false; reasonable, fair, or justifiable.","Students raised a legitimate concern about the unclear deadline.","lawful, genuine, valid","illegal, false, invalid","⚖️ ✅","Lawful, genuine, or reasonably justified","a legitimate concern","Legitimate can confirm legal status, authenticity, or a valid reason."],
  [15,"mirth","n.","happiness, laughter, and cheerful amusement.","The children's harmless performance filled the room with mirth.","laughter, merriment, amusement","sadness, gloom, misery","😂 🎉","Joy expressed through laughter","full of mirth","Mirth is a literary or formal word for cheerful laughter and enjoyment."],
  [15,"officiate","v.","to perform the official duties at a ceremony, religious service, sporting event, or other formal occasion.","A qualified referee will officiate at the championship match.","preside, conduct, referee","attend, observe, participate","🧑‍⚖️ 🏟️","Serving as the official in charge","officiate at a ceremony","Officiate at is used for events; officiate is also used without a preposition in sports."],
  [15,"partial","adj.","incomplete or affecting only part of something; unfairly favouring one side; especially fond of something.","The report offered only a partial explanation of what had happened.","incomplete; biased; fond","complete; impartial; averse","◐ ⚖️","Incomplete, biased, or especially fond","a partial solution","Partial to means fond of; partial toward means biased in favour of someone."],
  [15,"patronize","v.","to treat someone as if they are less intelligent or important; to regularly visit or buy from a business; to support an organisation, artist, or activity.","Please explain the process clearly without trying to patronize the new students.","condescend to; frequent; support","respect, avoid, boycott","🏪 👎","Supporting a business—or speaking down to someone","patronize a local shop","Context determines whether patronize means support a business or treat someone condescendingly."],
  [15,"rite","n.","a formal ceremony or customary act, especially one connected with religion or an important stage of life.","The community observed the traditional rite with dignity and respect.","ceremony, ritual, observance","informality, neglect, ordinary action","🕯️ 📜","A formal traditional or religious ceremony","a rite of passage","Rite means ceremony; right and write have different meanings although they sound the same."],
  [15,"sagacious","adj.","having or showing sound judgement, practical wisdom, and the ability to understand difficult situations.","The sagacious leader listened carefully before offering a fair solution.","wise, discerning, shrewd","foolish, shortsighted, unwise","🦉 💡","Showing excellent wisdom and judgement","sagacious advice","Sagacious is a formal word praising deep, practical wisdom rather than mere knowledge." ]
);

practiceRows.push(
  ["authoritative",["The researcher cited an ______ medical reference.","Her calm, ______ voice brought the meeting to order.","Use an ______ source when checking an important fact."],["cynical","partial","harmonious"]],
  ["bankrupt",["Without new investment, the struggling company may go ______.","The failed project nearly ______ the small business.","Critics called the corrupt system morally ______."],["hardy","legitimate","sagacious"]],
  ["clamor",["A sudden ______ arose from the crowded stadium.","Residents began to ______ for safer roads.","The public ______ for action grew louder each day."],["mirth","feud","rite"]],
  ["coincide",["The two school events ______ on the same date.","His description did not ______ with the available evidence.","The beginning of the holiday will ______ with the end of examinations."],["officiate","haggle","patronize"]],
  ["cynical",["His ______ remark suggested that nobody ever acts generously.","The student became ______ after hearing many broken promises.","A ______ observer might question the organisation's motives."],["sagacious","harmonious","authoritative"]],
  ["despot",["The cruel ______ punished anyone who questioned his rule.","Citizens united peacefully against the oppressive ______.","History remembers the ruler as a ruthless ______."],["legacy","patronize","officiate"]],
  ["feud",["A minor argument developed into a bitter family ______.","The neighbours ended their long ______ through mediation.","The two leaders continued to ______ over control of the organisation."],["clamor","mirth","rite"]],
  ["haggle",["Tourists may ______ with merchants over the final price.","They continued to ______ until both sides accepted the terms.","After a short ______, the buyer and seller reached an agreement."],["coincide","officiate","patronize"]],
  ["hardy",["Only ______ plants can survive this severe winter.","The ______ hikers continued despite the difficult conditions.","This ______ breed is known for its strength and endurance."],["indisposed","partial","harmonious"]],
  ["harmonious",["The choir produced a rich and ______ sound.","The two communities developed a ______ relationship.","The colours formed a calm, ______ combination."],["cynical","partial","bankrupt"]],
  ["hoard",["The collector kept a secret ______ of rare coins.","It is unfair to ______ essential supplies during a shortage.","Squirrels ______ food to prepare for colder months."],["legacy","mirth","rite"]],
  ["indisposed",["The manager was ______ and could not attend the meeting.","Feeling slightly ______, he decided to rest at home.","The committee seemed ______ to reconsider its decision."],["hardy","harmonious","sagacious"]],
  ["legacy",["The teacher's greatest ______ was the confidence he gave his students.","The ancient building is part of the city's cultural ______.","She received a small ______ through her grandfather's will."],["hoard","rite","mirth"]],
  ["legitimate",["The customer made a ______ complaint about the damaged product.","The document proved that the business was ______.","Officials confirmed that the message came from a ______ source."],["bankrupt","cynical","partial"]],
  ["mirth",["The funny story filled the room with ______.","His eyes shone with ______ as everyone began to laugh.","The celebration was an evening of music and ______."],["clamor","feud","rite"]],
  ["officiate",["An experienced referee will ______ at the final match.","The judge was invited to ______ at the formal ceremony.","Only a licensed official may ______ at the event."],["haggle","coincide","patronize"]],
  ["partial",["The storm caused ______ damage to the roof.","A judge must not be ______ toward either side.","My grandfather is especially ______ to strong Arabic coffee."],["harmonious","legitimate","authoritative"]],
  ["patronize",["Many residents ______ the family-owned shop each week.","Do not ______ people by speaking as if they cannot understand.","The arts centre encourages residents to ______ local craftspeople."],["officiate","haggle","coincide"]],
  ["rite",["The ceremony marked an important ______ of passage.","Each traditional ______ was performed with respect.","The community preserved the ancient ______ for future generations."],["legacy","hoard","mirth"]],
  ["sagacious",["The council followed the elder's ______ advice.","Her ______ decision prevented a much larger problem.","A ______ judge considers both immediate and long-term consequences."],["cynical","indisposed","hardy"]]
);

audioRows.push(
  ["authoritative","","əˈθɔːr.ə.teɪ.t̬ɪv"],["bankrupt","","ˈbæŋ.krʌpt"],["clamor","","ˈklæm.ɚ"],
  ["coincide","","ˌkoʊ.ɪnˈsaɪd"],["cynical","","ˈsɪn.ɪ.kəl"],["despot","","ˈdes.pət"],
  ["feud","","fjuːd"],["haggle","","ˈhæɡ.əl"],["hardy","","ˈhɑːr.di"],
  ["harmonious","","hɑːrˈmoʊ.ni.əs"],["hoard","","hɔːrd"],["indisposed","us_pron/u/usi/usind/usindia011.mp3","ˌɪn.dɪˈspoʊzd"],
  ["legacy","","ˈleɡ.ə.si"],["legitimate","","ləˈdʒɪt̬.ə.mət"],["mirth","","mɝːθ"],
  ["officiate","us_pron/e/eus/eus75/eus75175.mp3","əˈfɪʃ.i.eɪt"],["partial","","ˈpɑːr.ʃəl"],["patronize","","ˈpeɪ.trə.naɪz"],
  ["rite","us_pron/r/rig/right/right.mp3","raɪt"],["sagacious","us_pron/u/uss/ussac/ussackc025.mp3","səˈɡeɪ.ʃəs"]
);
