// Level B, Unit 10. Includes multiple meanings, context practice, and offline IPA.
vocabRows.push(
  [10,"bellow","v., n.","(v.) to shout in a deep, loud voice; to make a deep roar like a large animal; (n.) a deep, loud shout or roar.","The coach had to bellow instructions above the noise of the storm.","roar, shout, boom","whisper, murmur, speak softly","🗣️ 📣","A very deep and powerful shout","bellow with laughter","Bellow usually suggests a loud, deep sound made by a person or a large animal."],
  [10,"beneficiary","n.","a person or organisation that receives money, property, help, or another benefit.","Each scholarship beneficiary received support for books and school fees.","recipient, heir, receiver","donor, giver, benefactor","🎁 🙋","Someone who receives a benefit","the main beneficiary","A beneficiary may receive help from a programme, money from insurance, or property through a will or trust."],
  [10,"botch","v., n.","(v.) to do or repair something badly or carelessly; (n.) a badly performed job or a clumsy mistake.","Rushing the measurements could cause us to botch the entire project.","bungle, spoil, mishandle","perfect, repair, accomplish","🛠️ ❌","Doing a job so badly that it is spoiled","botch the job","A botched task is damaged by careless or unskilful work."],
  [10,"clutter","n., v.","(n.) a disorderly collection of things; (v.) to fill a place untidily or make it crowded and confusing.","Removing unnecessary clutter made the study area calmer and easier to use.","mess, disorder, jumble","order, neatness, organisation","📚 🧩","Too many things creating a mess","clutter the desk","Clutter may be physical objects or unnecessary information that makes something difficult to understand."],
  [10,"dilapidated","adj.","in poor condition because of age, damage, or neglect; partly ruined.","The council repaired the dilapidated building before reopening it as a library.","run-down, decayed, ramshackle","sound, maintained, renovated","🏚️ 🔨","An old structure falling into disrepair","a dilapidated house","Dilapidated is normally used for buildings, vehicles, or objects that have not been maintained."],
  [10,"dismantle","v.","to take something apart piece by piece; to end or remove a system or organisation gradually.","The technicians will dismantle the machine before moving it safely.","disassemble, take apart, break down","assemble, build, construct","⚙️ 🧰","Taking something carefully into separate parts","dismantle a machine","Dismantle can refer to physical objects or to removing systems, rules, and organisations."],
  [10,"farce","n.","a comedy based on exaggerated, unlikely situations; an event or situation that is so badly organised or unreasonable that it becomes ridiculous.","The confused meeting became a farce because nobody knew who was responsible.","comedy, mockery, absurdity","seriousness, reality, order","🎭 😵","A ridiculous comedy or absurd situation","a complete farce","Calling a real event a farce strongly criticises it as meaningless or badly managed."],
  [10,"futile","adj.","unable to produce a useful result; pointless or ineffective.","It was futile to continue searching the empty room after every corner had been checked.","useless, pointless, ineffective","useful, effective, successful","🔄 🚫","Effort that cannot achieve its purpose","a futile attempt","Futile describes an action whose desired result cannot be achieved."],
  [10,"grueling","adj.","extremely tiring and demanding; requiring great physical or mental effort.","The rescue team completed a grueling climb through difficult conditions.","exhausting, punishing, demanding","easy, relaxing, effortless","⛰️ 😓","A task that uses nearly all your energy","a grueling schedule","Grueling is the American spelling; gruelling is the British spelling."],
  [10,"hospitable","adj.","friendly and generous toward guests; providing conditions in which people, plants, or animals can live or grow.","The hospitable family welcomed the travellers and offered them refreshments.","welcoming, friendly, accommodating","unfriendly, hostile, unwelcoming","🏠 🤝","Warmly welcoming guests or supporting life","hospitable to visitors","A place can also be hospitable when its conditions support life or growth."],
  [10,"lair","n.","the resting or hiding place of a wild animal; a secret or private hiding place used by a person.","Tracks in the mud led the wildlife officer toward the animal's lair.","den, hideout, shelter","open space, exposure","🐾 🕳️","A hidden resting place or den","a lion's lair","Lair often suggests a hidden place belonging to an animal or, figuratively, a secretive person."],
  [10,"lavish","adj., v.","(adj.) very generous, abundant, rich, or expensive; (v.) to give something in large or generous amounts.","The volunteers received lavish praise for their service to the community.","generous, abundant, luxurious","meagre, modest, sparse","🎁 ✨","Giving or displaying more than enough","lavish praise on","Lavish can suggest generous abundance, but it may also imply unnecessary expense."],
  [10,"morbid","adj.","showing an unhealthy interest in death or disturbing subjects; gloomy; relating to disease or unhealthy conditions.","The teacher redirected the discussion when it became unnecessarily morbid.","gloomy, macabre, unhealthy","cheerful, wholesome, healthy","🌑 🩺","Unhealthily focused on death, gloom, or disease","morbid curiosity","In medicine, morbid means related to disease; in everyday use it often describes disturbing or gloomy interest."],
  [10,"notorious","adj.","widely known for something bad, harmful, or unfavourable.","The crossing was notorious for heavy traffic and poor visibility.","infamous, disreputable, ill-famed","respected, reputable, honourable","⚠️ 📰","Famous for a bad reason","notorious for","Notorious is negative; use famous or renowned when the reputation is positive."],
  [10,"pamper","v.","to treat with excessive comfort, attention, or indulgence; to care for in a luxurious way.","The hotel promised to pamper its guests with excellent service.","indulge, spoil, coddle","neglect, deprive, discipline","🛁 👑","Giving someone more comfort and attention than necessary","pamper yourself","Pamper may be positive when it means special care, but negative when indulgence prevents responsibility."],
  [10,"parasite","n.","an organism that lives on or in another organism and takes nourishment from it, often causing harm; a person who depends unfairly on others.","The scientist examined how the parasite affected the plant's growth.","pest, freeloader, exploiter","host, provider, contributor","🦠 🌿","Living by taking from a host","a harmful parasite","The biological meaning is scientific; the figurative meaning for a person is strongly insulting."],
  [10,"shirk","v.","to avoid or neglect a duty, responsibility, or difficult task.","A dependable team member does not shirk responsibility when problems arise.","avoid, evade, dodge","accept, undertake, fulfil","🙈 📋","Trying to escape a responsibility","shirk one's duties","Shirk normally takes an object such as duty, work, or responsibility."],
  [10,"surplus","n., adj.","(n.) an amount left over after needs have been met; (adj.) more than is needed or required.","The food bank distributed the farm's surplus vegetables to local families.","excess, remainder, extra","shortage, deficit, lack","➕ 📦","More than the amount needed","a budget surplus","Surplus may refer to money, supplies, products, workers, or any amount beyond what is required."],
  [10,"timidity","n.","lack of courage, confidence, or willingness to take reasonable risks.","With practice and encouragement, his timidity during presentations gradually disappeared.","shyness, fearfulness, hesitation","boldness, courage, confidence","🐭 🙊","Holding back because of fear or low confidence","overcome timidity","Timidity is stronger than simple quietness because it involves fear or lack of confidence."],
  [10,"veto","n., v.","(n.) an official power or act of rejecting a proposal or decision; (v.) to reject or prohibit officially.","The council president used a veto to prevent the proposal from becoming policy.","rejection, prohibition; reject, block","approval, consent; approve, permit","🛑 📜","An official decision that blocks a proposal","veto a bill","A veto is more formal and authoritative than an ordinary disagreement." ]
);

practiceRows.push(
  ["bellow",["The captain had to ______ orders above the roaring wind.","A deep ______ echoed from the bull across the field.","Do not ______ across the room when you can speak calmly."],["shirk","pamper","botch"]],
  ["beneficiary",["The hospital was the main ______ of the charity campaign.","She was named as a ______ in her grandfather's will.","Every programme ______ received books and learning materials."],["parasite","lair","surplus"]],
  ["botch",["Careless cutting could ______ the final model.","The rushed repair was a complete ______ and had to be repeated.","Read the instructions first so that you do not ______ the installation."],["dismantle","clutter","shirk"]],
  ["clutter",["Stacks of unused paper created ______ on the desk.","Too many decorations can ______ a small classroom.","Remove visual ______ so the main information is easy to find."],["surplus","lair","farce"]],
  ["dilapidated",["The ______ warehouse had broken windows and a damaged roof.","Workers restored the ______ bus before using it again.","Years of neglect left the once-fine house ______."],["hospitable","lavish","notorious"]],
  ["dismantle",["Engineers had to ______ the bridge section by section.","Please ______ the display carefully and store each piece.","The reform was designed to ______ an unfair system."],["botch","clutter","pamper"]],
  ["farce",["The play was a lively ______ full of exaggerated misunderstandings.","Because the rules were ignored, the competition became a ______.","The disorganised hearing was criticised as a complete ______."],["clutter","lair","surplus"]],
  ["futile",["It was ______ to argue after the final evidence had been confirmed.","Without water, their attempt to grow the plants was ______.","Trying the same broken key again seemed ______."],["grueling","hospitable","lavish"]],
  ["grueling",["The athletes completed a ______ training session in the heat.","Preparing the emergency centre was a ______ all-night task.","After the ______ journey, the travellers needed several hours of rest."],["futile","lavish","hospitable"]],
  ["hospitable",["Our ______ hosts made every visitor feel comfortable.","The mild climate is ______ to many kinds of plants.","They thanked the family for being so warm and ______."],["notorious","morbid","dilapidated"]],
  ["lair",["The bear returned to its hidden ______ before sunset.","The detectives discovered the thieves' secret ______.","The animal dragged leaves into its forest ______."],["clutter","surplus","parasite"]],
  ["lavish",["The audience offered ______ praise after the excellent performance.","The palace was decorated in a ______ style.","The mentor continued to ______ attention on the promising project."],["futile","surplus","dilapidated"]],
  ["morbid",["His ______ curiosity led him to focus only on disturbing details.","The story's dark setting created a ______ mood.","Researchers recorded the disease's ______ effects on the tissue."],["hospitable","lavish","notorious"]],
  ["notorious",["The road is ______ for dangerous bends during heavy rain.","The criminal became ______ after his actions appeared in the news.","That website is ______ for spreading inaccurate information."],["hospitable","beneficiary","timidity"]],
  ["pamper",["The spa aims to ______ guests with comfort and attentive service.","Grandparents sometimes ______ children with extra treats.","It is enjoyable to ______ yourself occasionally after working hard."],["shirk","dismantle","veto"]],
  ["parasite",["The tick is a ______ that feeds on the blood of its host.","A plant ______ was weakening the tree by taking its nutrients.","The laboratory identified the ______ under a microscope."],["beneficiary","surplus","lair"]],
  ["shirk",["Good citizens should not ______ their responsibilities.","He tried to ______ the difficult task by pretending to be busy.","A reliable captain will never ______ a duty to the team."],["pamper","botch","bellow"]],
  ["surplus",["The school donated its ______ computers to another centre.","After all bills were paid, the club had a small budget ______.","A ______ of tomatoes caused prices to fall at the market."],["clutter","beneficiary","lair"]],
  ["timidity",["Her ______ prevented her from asking the necessary question.","Regular speaking practice helped him overcome his ______.","The shy puppy gradually lost its ______ around visitors."],["notorious","morbid","veto"]],
  ["veto",["The president may ______ the proposed law.","One permanent member used its ______ to block the resolution.","The committee chair cannot simply ______ a decision without authority."],["lavish","pamper","shirk"]]
);

audioRows.push(
  ["bellow","","ˈbel.oʊ"],["beneficiary","us_pron/e/eus/eus70/eus70508.mp3","ˌben.əˈfɪʃ.i.er.i"],["botch","","bɑːtʃ"],
  ["clutter","","ˈklʌt̬.ɚ"],["dilapidated","","dɪˈlæp.ə.deɪ.t̬ɪd"],["dismantle","","dɪˈsmæn.t̬əl"],
  ["farce","","fɑːrs"],["futile","","ˈfjuː.t̬əl"],["grueling","","ˈɡruː.ə.lɪŋ"],
  ["hospitable","","hɑːˈspɪt̬.ə.bəl"],["lair","","ler"],["lavish","","ˈlæv.ɪʃ"],
  ["morbid","","ˈmɔːr.bɪd"],["notorious","","noʊˈtɔːr.i.əs"],["pamper","","ˈpæm.pɚ"],
  ["parasite","","ˈper.ə.saɪt"],["shirk","","ʃɝːk"],["surplus","","ˈsɝː.pləs"],
  ["timidity","","tɪˈmɪd.ə.t̬i"],["veto","","ˈviː.t̬oʊ"]
);
